import type { FocusFlowDSL } from '@focusflow/dsl';

export const realtimeLakehouseTemplate: FocusFlowDSL = {
  $schema: 'https://focusflow.io/schema/v1.json',
  meta: {
    title: '实时流批一体湖仓与智能分析拓扑',
    viewport: { width: 3840, height: 2160 },
    theme: { mode: 'dark', accent: '#34d399' },
    controls: { showHUDButton: true, autoplay: false, interval: 4000 },
  },
  asset: {
    url: './templates/realtime-lakehouse.svg',
  },
  elements: {
    boxes: [
      {
        id: 'box-cdc-ingest',
        type: 'rect',
        x: 300,
        y: 600,
        width: 650,
        height: 460,
        rx: 16,
        style: { stroke: '#38bdf8', strokeWidth: 4, glow: true },
      },
      {
        id: 'box-kafka-bus',
        type: 'rect',
        x: 1200,
        y: 600,
        width: 750,
        height: 460,
        rx: 16,
        style: { stroke: '#34d399', strokeWidth: 4, glow: true },
      },
      {
        id: 'box-flink-engine',
        type: 'rect',
        x: 2150,
        y: 600,
        width: 700,
        height: 460,
        rx: 16,
        style: { stroke: '#fbbf24', strokeWidth: 4, glow: true },
      },
      {
        id: 'box-lakehouse-olap',
        type: 'rect',
        x: 3050,
        y: 600,
        width: 650,
        height: 460,
        rx: 16,
        style: { stroke: '#818cf8', strokeWidth: 4, glow: true },
      },
      {
        id: 'box-upstream-sources',
        type: 'rect',
        x: 300,
        y: 240,
        width: 650,
        height: 180,
        rx: 16,
        style: { stroke: '#38bdf8', strokeWidth: 2, glow: false },
      },
      {
        id: 'box-realtime-bi',
        type: 'rect',
        x: 2150,
        y: 240,
        width: 1550,
        height: 120,
        rx: 14,
        style: { stroke: '#818cf8', strokeWidth: 2, glow: false },
      },
      {
        id: 'box-parquet-storage',
        type: 'rect',
        x: 300,
        y: 1180,
        width: 1100,
        height: 240,
        rx: 16,
        style: { stroke: '#38bdf8', strokeWidth: 2, glow: false },
      },
      {
        id: 'box-feature-store',
        type: 'rect',
        x: 1500,
        y: 1180,
        width: 1150,
        height: 240,
        rx: 16,
        style: { stroke: '#fbbf24', strokeWidth: 2, glow: false },
      },
    ],
    paths: [
      {
        id: 'path-cdc-to-kafka',
        from: 'box-cdc-ingest.right',
        to: 'box-kafka-bus.left',
        style: { stroke: '#34d399', strokeWidth: 4, mode: 'stream', flowSpeed: 2.0 },
      },
      {
        id: 'path-kafka-to-flink',
        from: 'box-kafka-bus.right',
        to: 'box-flink-engine.left',
        style: { stroke: '#fbbf24', strokeWidth: 4, mode: 'stream', flowSpeed: 2.2 },
      },
      {
        id: 'path-flink-to-lakehouse',
        from: 'box-flink-engine.right',
        to: 'box-lakehouse-olap.left',
        style: { stroke: '#818cf8', strokeWidth: 4, mode: 'stream', flowSpeed: 2.0 },
      },
      {
        id: 'path-sources-to-cdc',
        from: 'box-upstream-sources.bottom',
        to: 'box-cdc-ingest.top',
        style: { stroke: '#38bdf8', strokeWidth: 3, mode: 'stream', flowSpeed: 1.5 },
      },
      {
        id: 'path-flink-to-bi',
        from: 'box-flink-engine.top',
        to: 'box-realtime-bi.bottom',
        style: { stroke: '#fbbf24', strokeWidth: 3, mode: 'stream', flowSpeed: 1.8 },
      },
      {
        id: 'path-lakehouse-to-storage',
        from: 'box-lakehouse-olap.bottom',
        to: 'box-parquet-storage.top',
        style: { stroke: '#818cf8', strokeWidth: 3, mode: 'stream', flowSpeed: 1.6 },
      },
    ],
  },
  scenes: [
    {
      id: 'scene-1',
      title: '01 实时流批一体湖仓全链路拓扑总览',
      camera: { zoom: 1.0, x: 0, y: 0, duration: 1.2 },
      activeElements: {
        boxes: [
          'box-cdc-ingest',
          'box-kafka-bus',
          'box-flink-engine',
          'box-lakehouse-olap',
          'box-upstream-sources',
          'box-realtime-bi',
          'box-parquet-storage',
          'box-feature-store',
        ],
        paths: [
          'path-cdc-to-kafka',
          'path-kafka-to-flink',
          'path-flink-to-lakehouse',
          'path-sources-to-cdc',
          'path-flink-to-bi',
          'path-lakehouse-to-storage',
        ],
        callouts: [
          {
            id: 'co-lh-overview',
            targetBoxId: 'box-kafka-bus',
            position: { left: '1220px', top: '510px' },
            theme: 'green',
            title: '实时流批一体湖仓枢纽',
            desc: 'Debezium CDC 采集 ➔ Kafka 削峰总线 ➔ Flink 实时计算 ➔ Iceberg 湖仓入库与 ClickHouse 秒级 OLAP',
          },
        ],
      },
    },
    {
      id: 'scene-2',
      title: '02 CDC 增量抽取与 Kafka KRaft 高并发事件总线',
      camera: { zoom: 1.85, x: -16, y: -4, duration: 1.4 },
      activeElements: {
        boxes: ['box-cdc-ingest', 'box-kafka-bus', 'box-upstream-sources'],
        paths: ['path-cdc-to-kafka', 'path-sources-to-cdc'],
        callouts: [
          {
            id: 'co-cdc',
            targetBoxId: 'box-cdc-ingest',
            position: { left: '320px', top: '510px' },
            theme: 'blue',
            title: '无锁日志增量捕获 (Debezium)',
            desc: '直接挖掘 MySQL/PG 底层日志，Schema 演进一致性校验，端到端吞吐 280,000 evt/s',
          },
          {
            id: 'co-kafka',
            targetBoxId: 'box-kafka-bus',
            position: { left: '1220px', top: '510px' },
            theme: 'green',
            title: 'Kafka KRaft 事务削峰缓冲',
            desc: '去 ZooKeeper 轻量仲裁，EOS 幂等生产杜绝重复乱序，分层冷热存储支撑 8.5 GB/s 带宽',
          },
        ],
      },
    },
    {
      id: 'scene-3',
      title: '03 Flink 状态化双流 Join 与 Iceberg / ClickHouse 湖仓分析',
      camera: { zoom: 1.85, x: 18, y: -4, duration: 1.4 },
      activeElements: {
        boxes: ['box-flink-engine', 'box-lakehouse-olap', 'box-realtime-bi'],
        paths: ['path-kafka-to-flink', 'path-flink-to-lakehouse', 'path-flink-to-bi'],
        callouts: [
          {
            id: 'co-flink',
            targetBoxId: 'box-flink-engine',
            position: { left: '2170px', top: '510px' },
            theme: 'amber',
            title: 'Flink 状态计算与 CEP 规则引擎',
            desc: 'RocksDB 增量状态后端处理 120 万 records/s，时间窗口双流对账延迟仅 12ms',
          },
          {
            id: 'co-iceberg',
            targetBoxId: 'box-lakehouse-olap',
            position: { left: '3070px', top: '510px' },
            theme: 'purple',
            title: 'Iceberg ACID 湖仓与 ClickHouse OLAP',
            desc: '行级 Upsert 与自动小文件 Compaction，百亿级数据复杂聚合查询 P90 低至 88ms',
          },
        ],
      },
    },
  ],
};
