import type { FocusFlowDSL } from '@focusflow/dsl';

export const microservicesTemplate: FocusFlowDSL = {
  $schema: 'https://focusflow.io/schema/v1.json',
  meta: {
    title: '微服务高可用电商中台演进架构',
    viewport: { width: 3840, height: 2160 },
    theme: { mode: 'dark', accent: '#38bdf8' },
    controls: { showHUDButton: true, autoplay: false, interval: 4200 },
  },
  asset: {
    url: './templates/microservices-architecture.svg',
  },
  elements: {
    boxes: [
      {
        id: 'box-ingress',
        type: 'rect',
        x: 400,
        y: 240,
        width: 600,
        height: 180,
        rx: 16,
        style: { stroke: '#38bdf8', strokeWidth: 2, glow: false },
      },
      {
        id: 'box-nacos',
        type: 'rect',
        x: 1400,
        y: 240,
        width: 700,
        height: 120,
        rx: 14,
        style: { stroke: '#38bdf8', strokeWidth: 2, glow: false },
      },
      {
        id: 'box-apm',
        type: 'rect',
        x: 2500,
        y: 240,
        width: 800,
        height: 120,
        rx: 14,
        style: { stroke: '#f43f5e', strokeWidth: 2, glow: false },
      },
      {
        id: 'box-gateway',
        type: 'rect',
        x: 400,
        y: 600,
        width: 600,
        height: 380,
        rx: 16,
        style: { stroke: '#38bdf8', strokeWidth: 4, glow: true },
      },
      {
        id: 'box-order-svc',
        type: 'rect',
        x: 1400,
        y: 400,
        width: 700,
        height: 400,
        rx: 16,
        style: { stroke: '#34d399', strokeWidth: 4, glow: true },
      },
      {
        id: 'box-stock-svc',
        type: 'rect',
        x: 1400,
        y: 1000,
        width: 700,
        height: 400,
        rx: 16,
        style: { stroke: '#fbbf24', strokeWidth: 4, glow: true },
      },
      {
        id: 'box-seata-tx',
        type: 'rect',
        x: 2500,
        y: 700,
        width: 800,
        height: 480,
        rx: 18,
        style: { stroke: '#f43f5e', strokeWidth: 5, glow: true },
      },
      {
        id: 'box-kafka-bus',
        type: 'rect',
        x: 400,
        y: 1540,
        width: 850,
        height: 240,
        rx: 16,
        style: { stroke: '#38bdf8', strokeWidth: 2, glow: false },
      },
      {
        id: 'box-db-sharding',
        type: 'rect',
        x: 1350,
        y: 1540,
        width: 900,
        height: 240,
        rx: 16,
        style: { stroke: '#34d399', strokeWidth: 2, glow: false },
      },
      {
        id: 'box-es-search',
        type: 'rect',
        x: 2350,
        y: 1540,
        width: 950,
        height: 240,
        rx: 16,
        style: { stroke: '#818cf8', strokeWidth: 2, glow: false },
      },
    ],
    paths: [
      {
        id: 'path-ingress-gw',
        from: 'box-ingress.bottom',
        to: 'box-gateway.top',
        style: { stroke: '#38bdf8', strokeWidth: 3, mode: 'stream', flowSpeed: 1.6 },
      },
      {
        id: 'path-gw-order',
        from: 'box-gateway.right',
        to: 'box-order-svc.left',
        style: { stroke: '#38bdf8', strokeWidth: 3, mode: 'stream', flowSpeed: 1.8 },
      },
      {
        id: 'path-order-stock',
        from: 'box-order-svc.bottom',
        to: 'box-stock-svc.top',
        style: { stroke: '#34d399', strokeWidth: 3, mode: 'stream', flowSpeed: 1.6 },
      },
      {
        id: 'path-order-seata',
        from: 'box-order-svc.right',
        to: 'box-seata-tx.left',
        style: { stroke: '#34d399', strokeWidth: 3, mode: 'stream', flowSpeed: 2.0 },
      },
      {
        id: 'path-stock-seata',
        from: 'box-stock-svc.right',
        to: 'box-seata-tx.left',
        style: { stroke: '#fbbf24', strokeWidth: 3, mode: 'stream', flowSpeed: 1.8 },
      },
      {
        id: 'path-order-kafka',
        from: 'box-order-svc.bottom',
        to: 'box-kafka-bus.top',
        style: { stroke: '#38bdf8', strokeWidth: 3, mode: 'stream', flowSpeed: 1.5 },
      },
      {
        id: 'path-seata-db',
        from: 'box-seata-tx.bottom',
        to: 'box-db-sharding.top',
        style: { stroke: '#f43f5e', strokeWidth: 3, mode: 'stream', flowSpeed: 2.0 },
      },
    ],
  },
  scenes: [
    {
      id: 'scene-1',
      title: '01 微服务电商全局拓扑',
      titleI18n: {
        zh: '01 微服务电商全局拓扑',
        en: '01 Global Microservices Topology',
      },
      duration: 4500,
      voiceoverScript:
        '欢迎体验 FocusFlow 电商高可用微服务演进拓扑。本系统采用现代化云原生架构，涵盖 12 万 QPS 流量接入网关、高并发订单生命周期引擎、Redis Lua 内存防超卖库存中台，以及 Seata AT 分布式事务强一致性闭环。',
      voiceoverScriptI18n: {
        zh: '欢迎体验 FocusFlow 电商高可用微服务演进拓扑。本系统采用现代化云原生架构，涵盖 12 万 QPS 流量接入网关、高并发订单生命周期引擎、Redis Lua 内存防超卖库存中台，以及 Seata AT 分布式事务强一致性闭环。',
        en: 'Welcome to the FocusFlow high-availability e-commerce microservices topology. Powered by cloud-native design, this architecture covers 120k QPS ingress gateways, high-concurrency order lifecycle engines, Redis Lua anti-overselling inventory, and Seata AT distributed transaction consistency.',
      },
      camera: { zoom: 1.0, x: 0, y: 0, duration: 1.2 },
      activeElements: {
        boxes: [
          'box-ingress',
          'box-nacos',
          'box-apm',
          'box-gateway',
          'box-order-svc',
          'box-stock-svc',
          'box-seata-tx',
          'box-kafka-bus',
          'box-db-sharding',
          'box-es-search',
        ],
        paths: [
          'path-ingress-gw',
          'path-gw-order',
          'path-order-stock',
          'path-order-seata',
          'path-stock-seata',
          'path-order-kafka',
          'path-seata-db',
        ],
        callouts: [
          {
            id: 'co-ms-overview',
            targetBoxId: 'box-gateway',
            position: { left: '440px', top: '520px' },
            theme: 'blue',
            title: '微服务电商中台枢纽',
            desc: 'APISIX 网关集群 ➔ 订单状态机 ➔ 库存原子防超卖 ➔ Seata AT 2PC 事务闭环',
            titleI18n: {
              zh: '微服务电商中台枢纽',
              en: 'Microservices E-Commerce Hub',
            },
            descI18n: {
              zh: 'APISIX 网关集群 ➔ 订单状态机 ➔ 库存原子防超卖 ➔ Seata AT 2PC 事务闭环',
              en: 'APISIX Gateway ➔ Order State Machine ➔ Anti-Overselling Inventory ➔ Seata AT 2PC',
            },
          },
        ],
      },
    },
    {
      id: 'scene-2',
      title: '02 边缘接入与 API 网关集群治理',
      titleI18n: {
        zh: '02 边缘接入与 API 网关集群治理',
        en: '02 Edge Ingress & Gateway Cluster',
      },
      duration: 4200,
      voiceoverScript:
        '客户端多端流量经由 BGP Anycast CDN 进入 APISIX 网关集群。网关集成 Sentinel 实现动态滑动窗口限流与自适应熔断，配合 RSA 非对称公钥缓存，在边缘毫秒级完成 JWT 身份验证与 CASL 细粒度鉴权。',
      voiceoverScriptI18n: {
        zh: '客户端多端流量经由 BGP Anycast CDN 进入 APISIX 网关集群。网关集成 Sentinel 实现动态滑动窗口限流与自适应熔断，配合 RSA 非对称公钥缓存，在边缘毫秒级完成 JWT 身份验证与 CASL 细粒度鉴权。',
        en: 'Client traffic enters the APISIX gateway cluster via BGP Anycast CDN. Integrating Sentinel for sliding-window rate limiting and circuit breaking, the gateway verifies JWT tokens in sub-milliseconds using RSA public key caching and CASL fine-grained policies.',
      },
      camera: { zoom: 1.85, x: -28, y: -12, duration: 1.4 },
      activeElements: {
        boxes: ['box-ingress', 'box-gateway'],
        paths: ['path-ingress-gw', 'path-gw-order'],
        callouts: [
          {
            id: 'co-gw-sentinel',
            targetBoxId: 'box-gateway',
            position: { left: '440px', top: '520px' },
            theme: 'blue',
            title: 'Sentinel 动态限流与熔断',
            desc: '滑动窗口算法单 IP 限制 5,000 QPS，异常比例熔断毫秒级切流',
            titleI18n: {
              zh: 'Sentinel 动态限流与熔断',
              en: 'Sentinel Dynamic Rate Limiting',
            },
            descI18n: {
              zh: '滑动窗口算法单 IP 限制 5,000 QPS，异常比例熔断毫秒级切流',
              en: 'Sliding-window throttles up to 5,000 QPS/IP; sub-second circuit breaking on errors',
            },
          },
          {
            id: 'co-gw-jwt',
            targetBoxId: 'box-ingress',
            position: { left: '440px', top: '160px' },
            theme: 'blue',
            title: '全渠道 BGP CDN 与零信任鉴权',
            desc: 'iOS/Android/Web 统一域名接入，RSA 非对称密钥在网关本地极速验签',
            titleI18n: {
              zh: '全渠道 BGP CDN 与零信任鉴权',
              en: 'Omnichannel CDN & Zero-Trust Auth',
            },
            descI18n: {
              zh: 'iOS/Android/Web 统一域名接入，RSA 非对称密钥在网关本地极速验签',
              en: 'Unified ingress via Anycast CDN; local fast RSA token verification at gateway',
            },
          },
        ],
      },
    },
    {
      id: 'scene-3',
      title: '03 订单中台微服务与状态机编排',
      titleI18n: {
        zh: '03 订单中台微服务与状态机编排',
        en: '03 Order Core & Lifecycle Engine',
      },
      duration: 4200,
      voiceoverScript:
        '订单服务作为 Seata 全局事务发起者，采用 64 位雪花算法生成毫秒单调递增的全局流水号；结合 Redis SetNX 与状态机引擎，在网络抖动和连击时实现确定性的下单幂等防重。',
      voiceoverScriptI18n: {
        zh: '订单服务作为 Seata 全局事务发起者，采用 64 位雪花算法生成毫秒单调递增的全局流水号；结合 Redis SetNX 与状态机引擎，在网络抖动和连击时实现确定性的下单幂等防重。',
        en: 'As the Seata global transaction initiator, the Order Service generates monotonically increasing IDs via 64-bit Snowflake algorithms. Combined with Redis SetNX and state machines, it enforces strict order deduplication and idempotency under network jitter.',
      },
      camera: { zoom: 2.05, x: -5, y: -18, duration: 1.4 },
      activeElements: {
        boxes: ['box-order-svc', 'box-nacos'],
        paths: ['path-gw-order', 'path-order-seata'],
        callouts: [
          {
            id: 'co-order-snowflake',
            targetBoxId: 'box-order-svc',
            position: { left: '1440px', top: '320px' },
            theme: 'green',
            title: '64位雪花全局唯一流水号',
            desc: '毫秒时间戳 + 机房 ID + 节点编号 + 递增序列，高并发每秒可生成 400 万唯一 ID',
            titleI18n: {
              zh: '64位雪花全局唯一流水号',
              en: '64-bit Snowflake Distributed ID',
            },
            descI18n: {
              zh: '毫秒时间戳 + 机房 ID + 节点编号 + 递增序列，高并发每秒可生成 400 万唯一 ID',
              en: 'Timestamp + DC + Node + Seq: generates over 4M unique sequential IDs per second',
            },
          },
          {
            id: 'co-order-idempotent',
            targetBoxId: 'box-order-svc',
            position: { left: '1780px', top: '320px' },
            theme: 'green',
            title: 'Redis SetNX 下单幂等护卫',
            desc: '客户端防重 Token 校验，拦截重复点击与超时重试，确保每笔订单只扣减一次',
            titleI18n: {
              zh: 'Redis SetNX 下单幂等护卫',
              en: 'Redis Idempotent Guard',
            },
            descI18n: {
              zh: '客户端防重 Token 校验，拦截重复点击与超时重试，确保每笔订单只扣减一次',
              en: 'Token verification eliminates duplicated clicks and ensures deterministic transitions',
            },
          },
        ],
      },
    },
    {
      id: 'scene-4',
      title: '04 库存防超卖与内存原子预扣引擎',
      titleI18n: {
        zh: '04 库存防超卖与内存原子预扣引擎',
        en: '04 Inventory & Anti-Overselling Engine',
      },
      duration: 4200,
      voiceoverScript:
        '面对秒杀洪峰，库存服务摒弃昂贵的数据库行锁，通过 Redis Lua 脚本在内存中实现毫秒级原子预扣减；结合 16 分段锁打散热点商品竞态，在保障绝对零超卖的前提下支撑 36,000 TPS 的峰值吞吐。',
      voiceoverScriptI18n: {
        zh: '面对秒杀洪峰，库存服务摒弃昂贵的数据库行锁，通过 Redis Lua 脚本在内存中实现毫秒级原子预扣减；结合 16 分段锁打散热点商品竞态，在保障绝对零超卖的前提下支撑 36,000 TPS 的峰值吞吐。',
        en: 'To withstand flash-sale spikes, the Inventory Service avoids heavy database row locks by using Redis Lua scripts for in-memory atomic pre-deduction. Paired with 16-segment bucket locks, it ensures zero overselling while achieving 36,000 TPS peak throughput.',
      },
      camera: { zoom: 2.05, x: -5, y: 10, duration: 1.4 },
      activeElements: {
        boxes: ['box-stock-svc'],
        paths: ['path-order-stock', 'path-stock-seata'],
        callouts: [
          {
            id: 'co-stock-lua',
            targetBoxId: 'box-stock-svc',
            position: { left: '1440px', top: '920px' },
            theme: 'amber',
            title: 'Redis Lua 脚本原子内存扣减',
            desc: '单原子事务预查余额并扣减，扣减耗时仅 1.8ms，杜绝超卖并发穿透',
            titleI18n: {
              zh: 'Redis Lua 脚本原子内存扣减',
              en: 'Atomic Redis Lua Deduction',
            },
            descI18n: {
              zh: '单原子事务预查余额并扣减，扣减耗时仅 1.8ms，杜绝超卖并发穿透',
              en: 'Executes atomic pre-check and balance decrement in 1.8ms to eliminate overselling',
            },
          },
          {
            id: 'co-stock-bucket',
            targetBoxId: 'box-stock-svc',
            position: { left: '1780px', top: '920px' },
            theme: 'amber',
            title: 'Redisson 16 分段锁并发分流',
            desc: '将热点 SKU 总库存打散到 16 个分布式桶中，并发写入吞吐提升 16 倍',
            titleI18n: {
              zh: 'Redisson 16 分段锁并发分流',
              en: '16-Segment Bucket Concurrency',
            },
            descI18n: {
              zh: '将热点 SKU 总库存打散到 16 个分布式桶中，并发写入吞吐提升 16 倍',
              en: 'Splits hot SKU inventory across 16 sub-locks, scaling throughput 16x',
            },
          },
        ],
      },
    },
    {
      id: 'scene-5',
      title: '05 Seata AT 分布式事务与存储闭环',
      titleI18n: {
        zh: '05 Seata AT 分布式事务与存储闭环',
        en: '05 Seata AT 2PC & Distributed Storage',
      },
      duration: 4500,
      voiceoverScript:
        'Seata TC 统一管控跨微服务事务。RM 自动解析 SQL AST 并生成镜像快照。当下游发生支付失败或库存告罄时，TC 自动下发指令回放 Before Image 执行逆向补偿回滚，确保跨库跨服务的 100% 最终一致性。',
      voiceoverScriptI18n: {
        zh: 'Seata TC 统一管控跨微服务事务。RM 自动解析 SQL AST 并生成镜像快照。当下游发生支付失败或库存告罄时，TC 自动下发指令回放 Before Image 执行逆向补偿回滚，确保跨库跨服务的 100% 最终一致性。',
        en: 'The Seata TC coordinator manages cross-service transactions. Resource managers parse SQL ASTs to generate before and after images. If payment fails or stock runs out, TC triggers automatic rollback using undo logs, ensuring 100% eventual consistency across distributed databases.',
      },
      camera: { zoom: 1.9, x: 24, y: -2, duration: 1.5 },
      activeElements: {
        boxes: ['box-seata-tx', 'box-apm', 'box-db-sharding', 'box-kafka-bus'],
        paths: ['path-order-seata', 'path-stock-seata', 'path-seata-db', 'path-order-kafka'],
        callouts: [
          {
            id: 'co-seata-undo',
            targetBoxId: 'box-seata-tx',
            position: { left: '2540px', top: '620px' },
            theme: 'rose',
            title: 'Seata AT 自动 Undo Log 回滚',
            desc: '解析 SQL AST 自动生成反向补偿 SQL，业务无侵入，一阶段无感提交',
            titleI18n: {
              zh: 'Seata AT 自动 Undo Log 回滚',
              en: 'Seata AT Automated Undo Log',
            },
            descI18n: {
              zh: '解析 SQL AST 自动生成反向补偿 SQL，业务无侵入，一阶段无感提交',
              en: 'Parses SQL AST to auto-generate compensation rollbacks with zero business intrusion',
            },
          },
          {
            id: 'co-seata-raft',
            targetBoxId: 'box-seata-tx',
            position: { left: '2900px', top: '620px' },
            theme: 'rose',
            title: 'Raft 3节点高可用集群',
            desc: 'TC 服务自组 Raft Quorum 仲裁，节点宕机亚秒级选主，事务状态零丢失',
            titleI18n: {
              zh: 'Raft 3节点高可用集群',
              en: 'Raft 3-Node HA Cluster',
            },
            descI18n: {
              zh: 'TC 服务自组 Raft Quorum 仲裁，节点宕机亚秒级选主，事务状态零丢失',
              en: 'Self-hosted Raft quorum ensures sub-second leader failover and zero state loss',
            },
          },
        ],
      },
    },
  ],
};
