/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AcquireLockDto {
  /** Unique client session/tab identifier acquiring the lock */
  clientId: string;
  /**
     * Lease duration in seconds (default: 30s, min: 5s, max: 300s)
     * @minimum 5
     * @maximum 300
     */
  leaseSeconds?: number;
}
