/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Ledger action classification
 */
export type AdjustEntitlementBalanceDtoAction = typeof AdjustEntitlementBalanceDtoAction[keyof typeof AdjustEntitlementBalanceDtoAction];


export const AdjustEntitlementBalanceDtoAction = {
  GRANT_SUBSCRIPTION: 'GRANT_SUBSCRIPTION',
  GRANT_PURCHASE: 'GRANT_PURCHASE',
  GRANT_MANUAL: 'GRANT_MANUAL',
  ADMIN_COMPENSATION: 'ADMIN_COMPENSATION',
  CONSUME_TASK: 'CONSUME_TASK',
  REVOKE_EXPIRED: 'REVOKE_EXPIRED',
  REVOKE_REFUND: 'REVOKE_REFUND',
  REFUND_RESTORE: 'REFUND_RESTORE',
} as const;
