/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { AdjustEntitlementBalanceDtoAction } from './adjustEntitlementBalanceDtoAction';
import type { AdjustEntitlementBalanceDtoQuotaType } from './adjustEntitlementBalanceDtoQuotaType';

export interface AdjustEntitlementBalanceDto {
  /** Target workspace TypeID */
  workspaceId: string;
  /** Quota resource type to adjust */
  quotaType: AdjustEntitlementBalanceDtoQuotaType;
  /** Signed adjustment delta amount (positive to grant, negative to deduct) */
  changeAmount: number;
  /** Ledger action classification */
  action: AdjustEntitlementBalanceDtoAction;
  /** Associated external ticket or task ID */
  sourceId?: string;
  /** Mandatory operational reason for audit compliance */
  reason: string;
  /** Optional unique idempotency key to prevent double execution */
  idempotencyKey?: string;
}
