/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { AiChatCompletionDtoProvider } from './aiChatCompletionDtoProvider';
import type { ChatMessageDto } from './chatMessageDto';

export interface AiChatCompletionDto {
  /** Target workspace TypeID for tenant scoping and billing attribution */
  workspaceId?: string;
  /** Target AI vendor provider */
  provider?: AiChatCompletionDtoProvider;
  /** Model identifier name */
  model?: string;
  /**
     * List of conversation messages comprising the chat prompt
     * @minItems 1
     */
  messages: ChatMessageDto[];
  /**
     * Sampling temperature between 0.0 and 2.0
     * @minimum 0
     * @maximum 2
     */
  temperature?: number;
  /**
     * Maximum tokens to generate in response
     * @minimum 1
     */
  maxTokens?: number;
}
