/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AiChatUsageDto {
  /**
     * Number of tokens in the prompt / input
     * @minimum 0
     */
  inputTokens: number;
  /**
     * Number of tokens in the generated completion
     * @minimum 0
     */
  outputTokens: number;
  /**
     * Total tokens consumed (input + output)
     * @minimum 0
     */
  totalTokens: number;
}
