/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { AiChatUsageDto } from './aiChatUsageDto';
import type { ChatMessageDto } from './chatMessageDto';

export interface AiChatResponseDto {
  /** Unique completion request TypeID or UUID */
  id: string;
  /** AI provider used for completion */
  provider: string;
  /** Specific model employed */
  model: string;
  /** Generated assistant response message */
  message: ChatMessageDto;
  /** Token breakdown usage details */
  usage: AiChatUsageDto;
  /**
     * Total execution duration in milliseconds
     * @minimum 0
     */
  durationMs: number;
}
