/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Target AI vendor provider
 */
export type AiChatCompletionDtoProvider = typeof AiChatCompletionDtoProvider[keyof typeof AiChatCompletionDtoProvider];


export const AiChatCompletionDtoProvider = {
  AZURE_OPENAI: 'AZURE_OPENAI',
  OPENAI: 'OPENAI',
  ANTHROPIC: 'ANTHROPIC',
  DEEPSEEK: 'DEEPSEEK',
  ELEVENLABS: 'ELEVENLABS',
  VOLCENGINE: 'VOLCENGINE',
} as const;
