/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AiProviderConfigResponseDto {
  /** AI Provider Config TypeID */
  id: string;
  /** Provider name */
  provider: string;
  /** Service capability type */
  serviceType: string;
  /** API endpoint URL */
  endpointUrl: string;
  /** Masked API key hash for verification */
  apiKeyHash: string;
  /** Configured model or voice name */
  modelName: string;
  /** Whether this is the default provider config */
  isDefault: boolean;
  /** Whether provider is currently active */
  isActive: boolean;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}
