/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AiTtsResponseDto {
  /** Base64 encoded audio binary content */
  audioBase64: string;
  /**
     * Count of characters synthesized
     * @minimum 0
     */
  audioChars: number;
  /** Audio format */
  format: string;
  /** Provider that executed synthesis */
  provider: string;
  /** Voice or model name utilized */
  modelName: string;
  /**
     * Total execution duration in milliseconds
     * @minimum 0
     */
  durationMs: number;
}
