/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Target audio encoding format
 */
export type AiTtsSynthesizeDtoFormat = typeof AiTtsSynthesizeDtoFormat[keyof typeof AiTtsSynthesizeDtoFormat];


export const AiTtsSynthesizeDtoFormat = {
  mp3: 'mp3',
  wav: 'wav',
  ogg: 'ogg',
} as const;
