/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { AiTtsSynthesizeDtoFormat } from './aiTtsSynthesizeDtoFormat';
import type { AiTtsSynthesizeDtoProvider } from './aiTtsSynthesizeDtoProvider';

export interface AiTtsSynthesizeDto {
  /** Target workspace TypeID for tenant scoping and billing attribution */
  workspaceId?: string;
  /** Target AI TTS provider */
  provider?: AiTtsSynthesizeDtoProvider;
  /** Text script to synthesize into audio speech */
  text: string;
  /** Voice persona name */
  voice?: string;
  /**
     * Speaking rate speed multiplier (0.5 to 2.0)
     * @minimum 0.25
     * @maximum 4
     */
  speed?: number;
  /** Target audio encoding format */
  format?: AiTtsSynthesizeDtoFormat;
}
