/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AiUsageLogResponseDto {
  /** Audit log TypeID */
  id: string;
  /** Parent Application TypeID */
  appId: string;
  /** Attributed workspace TypeID */
  workspaceId?: string;
  /** Invoking user TypeID */
  userId?: string;
  /** AI provider name */
  provider: string;
  /** Service capability type */
  serviceType: string;
  /** Model or voice utilized */
  modelName: string;
  /**
     * Input prompt tokens consumed
     * @minimum 0
     */
  inputTokens: number;
  /**
     * Output completion tokens consumed
     * @minimum 0
     */
  outputTokens: number;
  /**
     * Audio characters synthesized
     * @minimum 0
     */
  audioChars: number;
  /**
     * Attributed financial cost in cents
     * @minimum 0
     */
  costCents: number;
  /**
     * Latency duration in milliseconds
     * @minimum 0
     */
  durationMs: number;
  /** HTTP response status code */
  statusCode: number;
  /** Invocation timestamp */
  createdAt: string;
}
