/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { AiUsageLogResponseDto } from './aiUsageLogResponseDto';

export interface AiUsageLogListResponseDto {
  /** List of AI invocation audit logs */
  logs: AiUsageLogResponseDto[];
  /**
     * Total records matching filters
     * @minimum 0
     */
  total: number;
}
