/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AppContextResponseDto {
  /** Unique TypeID of the application */
  appId: string;
  /** Machine identifier code of the application */
  appCode: string;
  /** Human-readable name of the application */
  appName: string;
  /** Public API key associated with the application */
  appKey?: string;
  /** List of allowed CORS origins configured for the application */
  allowedOrigins: string[];
  /** Custom rate limit in requests per minute */
  rateLimitRpm?: number;
  /** Whether application is active and permitted to transact */
  isActive: boolean;
}
