/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AssetResponseDto {
  /** Asset unique TypeID */
  id: string;
  /** Parent Application TypeID */
  appId: string;
  /** Workspace TypeID */
  workspaceId: string;
  /** Associated Project TypeID */
  projectId?: string;
  /** Owner User TypeID */
  ownerId: string;
  /** Asset media type */
  type: string;
  /** Asset filename */
  name: string;
  /** MIME type */
  mimeType: string;
  /** Asset size in bytes */
  sizeBytes: string;
  /** Physical storage key */
  storageKey: string;
  /** Public access CDN URL */
  publicUrl: string;
  /** Upload status */
  uploadStatus: string;
  /** Width in pixels */
  width?: number;
  /** Height in pixels */
  height?: number;
  /** Audio duration in milliseconds */
  durationMs?: number;
  /** SHA-256 hash */
  hashSha256?: string;
  /** Confirmation timestamp */
  confirmedAt?: string;
  /** Creation timestamp */
  createdAt: string;
}
