/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AuthUserDto {
  /** User unique TypeID */
  id: string;
  /** User email address */
  email: string;
  /** Display name */
  name: string;
  /** Global system role */
  role: string;
  /** Commercial membership tier */
  tier: string;
  /** User avatar URL */
  avatarUrl?: string;
}
