/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokensDto } from './authTokensDto';
import type { AuthUserDto } from './authUserDto';
import type { AuthWorkspaceDto } from './authWorkspaceDto';

export interface AuthResponseDto {
  /** Issued JWT token pair */
  tokens: AuthTokensDto;
  /** Authenticated user profile */
  user: AuthUserDto;
  /** Active default workspace */
  workspace?: AuthWorkspaceDto;
}
