/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AuthTokensDto {
  /** JWT Access Token (15m validity) */
  accessToken: string;
  /** JWT Refresh Token (7d validity) */
  refreshToken: string;
  /** Token authorization scheme */
  tokenType: string;
  /**
     * Access token expiration time in seconds
     * @minimum 1
     */
  expiresIn: number;
}
