/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface AuthWorkspaceDto {
  /** Workspace unique TypeID */
  id: string;
  /** Workspace display name */
  name: string;
  /** Workspace URL-safe slug */
  slug: string;
  /** Member role within this workspace */
  role: string;
}
