/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { BridgeWebhookDtoRawPayload } from './bridgeWebhookDtoRawPayload';
import type { BridgeWebhookDtoStatus } from './bridgeWebhookDtoStatus';

export interface BridgeWebhookDto {
  /** Unique event identifier */
  eventId: string;
  /** Gateway identifier */
  gateway: string;
  /** Internal transaction number */
  transactionNo: string;
  /** Associated order number */
  orderNo: string;
  /** Webhook payment status */
  status: BridgeWebhookDtoStatus;
  /**
     * Paid amount in cents
     * @minimum 0
     */
  amountCents: number;
  /** Currency */
  currency: string;
  /** Channel gateway trade number */
  gatewayTradeNo: string;
  /** Raw payload from the third-party upstream webhook */
  rawPayload?: BridgeWebhookDtoRawPayload;
}
