/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Webhook payment status
 */
export type BridgeWebhookDtoStatus = typeof BridgeWebhookDtoStatus[keyof typeof BridgeWebhookDtoStatus];


export const BridgeWebhookDtoStatus = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;
