/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Role of the message author
 */
export type ChatMessageDtoRole = typeof ChatMessageDtoRole[keyof typeof ChatMessageDtoRole];


export const ChatMessageDtoRole = {
  system: 'system',
  user: 'user',
  assistant: 'assistant',
} as const;
