/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface ConfirmAssetUploadDto {
  /** Target workspace TypeID */
  workspaceId: string;
  /** Asset TypeID generated during presigned upload request */
  assetId: string;
  /**
     * Image width in pixels
     * @minimum 1
     */
  width?: number;
  /**
     * Image height in pixels
     * @minimum 1
     */
  height?: number;
  /**
     * Audio duration in milliseconds
     * @minimum 0
     */
  durationMs?: number;
  /** SHA-256 content checksum for deduplication and integrity */
  hashSha256?: string;
}
