/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInvoiceDtoType } from './createInvoiceDtoType';

export interface CreateInvoiceDto {
  /** Target order number to invoice */
  orderNo: string;
  /** Invoice title / buyer name */
  title: string;
  /** Tax registration number */
  taxNumber?: string;
  /** Invoice type */
  type?: CreateInvoiceDtoType;
}
