/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface CreateWorkspaceDto {
  /** Workspace display name */
  name: string;
  /** Unique URL slug for the workspace (auto-generated if omitted) */
  slug?: string;
  /** IANA timezone for workspace scheduling and billing */
  timezone?: string;
}
