/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Video target resolution
 */
export type CreateRenderJobDtoResolution = typeof CreateRenderJobDtoResolution[keyof typeof CreateRenderJobDtoResolution];


export const CreateRenderJobDtoResolution = {
  '4K': '4K',
  '2K': '2K',
  '1080P': '1080P',
} as const;
