/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface CreateShortlinkDto {
  /** Target destination URL or internal studio route to redirect to */
  targetUrl: string;
  /**
     * Custom slug (3-64 chars Base62/alphanumeric/dash/underscore). Generated automatically if omitted.
     * @pattern ^[a-zA-Z0-9_-]{3,64}$
     */
  slug?: string;
  /**
     * Optional resource classification (e.g. PROJECT, RENDER, INVOICE)
     * @maxLength 32
     */
  resourceType?: string;
  /**
     * Optional associated resource identifier
     * @maxLength 128
     */
  resourceId?: string;
  /** Optional expiration timestamp in ISO 8601 format */
  expiresAt?: string;
  /** Active status of the shortlink */
  isActive?: boolean;
}
