/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Invoice type
 */
export type CreateInvoiceDtoType = typeof CreateInvoiceDtoType[keyof typeof CreateInvoiceDtoType];


export const CreateInvoiceDtoType = {
  RECEIPT: 'RECEIPT',
  VAT_NORMAL: 'VAT_NORMAL',
  VAT_SPECIAL: 'VAT_SPECIAL',
} as const;
