/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Video framerate (30 or 60 fps)
 */
export type CreateRenderJobDtoFps = typeof CreateRenderJobDtoFps[keyof typeof CreateRenderJobDtoFps];


export const CreateRenderJobDtoFps = {
  NUMBER_30: 30,
  NUMBER_60: 60,
} as const;
