/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrderItemDto } from './createOrderItemDto';

export interface CreateOrderDto {
  /** Target workspace TypeID */
  workspaceId: string;
  /** Direct plan code subscription (e.g. PLAN_PRO_MONTHLY) */
  planCode?: string;
  /** Direct plan TypeID subscription (e.g. pln_01j...) */
  planId?: string;
  /** Custom items list for add-on packs or cart-style checkout */
  items?: CreateOrderItemDto[];
}
