/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProjectDtoDslJson } from './createProjectDtoDslJson';

export interface CreateProjectDto {
  /** Target workspace TypeID */
  workspaceId?: string;
  /** Project visual presentation title */
  title: string;
  /** URL-friendly unique slug identifier */
  slug?: string;
  /** Optional architecture overview or presentation description */
  description?: string;
  /** Canvas 5K background diagram image URL or cloud asset identifier */
  bgImageUrl?: string;
  /**
     * Nominal canvas natural viewport width in pixels (5K standard: 5120)
     * @minimum 1
     */
  viewportW?: number;
  /**
     * Nominal canvas natural viewport height in pixels (5K standard: 2880)
     * @minimum 1
     */
  viewportH?: number;
  /** Initial FocusFlow DSL v1.0 state tree definition */
  dslJson?: CreateProjectDtoDslJson;
  /** Whether the presentation is publicly viewable without authentication */
  isPublic?: boolean;
}
