/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProjectTemplateDtoDslJson } from './createProjectTemplateDtoDslJson';

export interface CreateProjectTemplateDto {
  /** Template display title */
  title: string;
  /** Detailed description of the architecture and presentation flow */
  description?: string;
  /** Architecture category classification (e.g. ARCHITECTURE, CLOUD_NATIVE, FINANCE) */
  category: string;
  /** Search and taxonomy tags */
  tags?: string[];
  /** Thumbnail SVG/PNG image asset URL */
  thumbnailUrl?: string;
  /** Background preview diagram URL for canvas presentation */
  previewUrl?: string;
  /** Complete FocusFlow DSL v1.0 state tree blueprint */
  dslJson: CreateProjectTemplateDtoDslJson;
  /** Whether marked as official Tumio curated template */
  isOfficial?: boolean;
  /** Whether template is publicly discoverable in template gallery */
  isPublic?: boolean;
}
