/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Service type capability
 */
export type CreateAiProviderConfigDtoServiceType = typeof CreateAiProviderConfigDtoServiceType[keyof typeof CreateAiProviderConfigDtoServiceType];


export const CreateAiProviderConfigDtoServiceType = {
  TTS: 'TTS',
  LLM_COMPLETION: 'LLM_COMPLETION',
  LLM_CHAT: 'LLM_CHAT',
} as const;
