/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrderItemDtoItemType } from './createOrderItemDtoItemType';

export interface CreateOrderItemDto {
  /** Item category type */
  itemType: CreateOrderItemDtoItemType;
  /** SKU or Plan identifier code */
  skuCode: string;
  /**
     * Purchase quantity
     * @minimum 1
     */
  quantity: number;
}
