/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProjectVersionDtoDslJson } from './createProjectVersionDtoDslJson';

export interface CreateProjectVersionDto {
  /** Milestone version description / release changelog notes */
  description?: string;
  /** Full FocusFlow DSL v1.0 state tree snapshot (if omitted, copies project live DSL) */
  dslJson?: CreateProjectVersionDtoDslJson;
  /**
     * Explicit milestone version number (if omitted, defaults to project live versionNo)
     * @minimum 1
     */
  versionNo?: number;
}
