/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateFormDefinitionDtoJsonSchema } from './createFormDefinitionDtoJsonSchema';
import type { DedupeConfigDto } from './dedupeConfigDto';

export interface CreateFormDefinitionDto {
  /** Target workspace TypeID */
  workspaceId?: string;
  /** Custom unique public form key */
  formKey?: string;
  /** Form display name */
  name: string;
  /** Allowed origin domain whitelist for embed/CORS submission */
  allowedDomains?: string[];
  /** Whether JSONSchema dynamic validation is enabled */
  isSchemaEnabled?: boolean;
  /** JSONSchema definition for dynamic payload validation */
  jsonSchema?: CreateFormDefinitionDtoJsonSchema;
  /** Deduplication configuration */
  dedupeConfig?: DedupeConfigDto;
  /** Whether Cloudflare Turnstile human verification is required */
  isTurnstileEnabled?: boolean;
  /** Whether form is open for receiving submissions */
  isActive?: boolean;
}
