/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Output container format
 */
export type CreateRenderJobDtoOutputFormat = typeof CreateRenderJobDtoOutputFormat[keyof typeof CreateRenderJobDtoOutputFormat];


export const CreateRenderJobDtoOutputFormat = {
  mp4: 'mp4',
  gif: 'gif',
} as const;
