/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateNotificationTemplateDtoChannel } from './createNotificationTemplateDtoChannel';

export interface CreateNotificationTemplateDto {
  /** Unique template business code */
  code: string;
  /** Dispatch delivery channel */
  channel: CreateNotificationTemplateDtoChannel;
  /** Optional template subject for email or notification title */
  subjectTpl?: string;
  /** Template content body supporting {{variable}} interpolation */
  contentTpl: string;
}
