/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRenderJobDtoFps } from './createRenderJobDtoFps';
import type { CreateRenderJobDtoOutputFormat } from './createRenderJobDtoOutputFormat';
import type { CreateRenderJobDtoResolution } from './createRenderJobDtoResolution';

export interface CreateRenderJobDto {
  /** Video target resolution */
  resolution: CreateRenderJobDtoResolution;
  /** Video framerate (30 or 60 fps) */
  fps?: CreateRenderJobDtoFps;
  /** Output container format */
  outputFormat?: CreateRenderJobDtoOutputFormat;
  /** Optional workspace TypeID override */
  workspaceId?: string;
}
