/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAiProviderConfigDtoProvider } from './createAiProviderConfigDtoProvider';
import type { CreateAiProviderConfigDtoServiceType } from './createAiProviderConfigDtoServiceType';

export interface CreateAiProviderConfigDto {
  /** AI vendor provider name */
  provider: CreateAiProviderConfigDtoProvider;
  /** Service type capability */
  serviceType: CreateAiProviderConfigDtoServiceType;
  /** Vendor endpoint API base URL */
  endpointUrl: string;
  /** Plain API secret token or key (will be securely hashed upon storage) */
  apiKey: string;
  /** Default target model or voice name */
  modelName: string;
  /** Whether this config serves as system default for the given service type */
  isDefault?: boolean;
  /** Whether this provider config is active and routable */
  isActive?: boolean;
}
