/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { DedupeConfigDtoStrategy } from './dedupeConfigDtoStrategy';

export interface DedupeConfigDto {
  /** Whether deduplication is enabled */
  enabled: boolean;
  /** Object paths to extract values from for deduplication hash */
  unique_paths: string[];
  /** Action on duplicate collision */
  strategy: DedupeConfigDtoStrategy;
}
