/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Action on duplicate collision
 */
export type DedupeConfigDtoStrategy = typeof DedupeConfigDtoStrategy[keyof typeof DedupeConfigDtoStrategy];


export const DedupeConfigDtoStrategy = {
  reject: 'reject',
  overwrite: 'overwrite',
} as const;
