/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { EntitlementDiscrepancyDetailDto } from './entitlementDiscrepancyDetailDto';

export interface EntitlementReconciliationSummaryDto {
  /** Total tenant entitlement records audited */
  totalEntitlementsAudited: number;
  /** Count of entitlements with perfect mathematical conservation and cache parity */
  matchedCount: number;
  /** Count of entitlements exhibiting delta discrepancy */
  discrepantCount: number;
  /** Whether SUM(Ledger.changeAmount) === Entitlement.balance holds 100% across all audited items */
  isMathematicallyConserved: boolean;
  /** Whether Redis dual-key model is in perfect agreement with PostgreSQL DB balance */
  isCacheConsistent: boolean;
  /** Detailed list of quota discrepancies and cache repair actions */
  discrepancies: EntitlementDiscrepancyDetailDto[];
}
