/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface EntitlementDiscrepancyDetailDto {
  /** Workspace identifier */
  workspaceId: string;
  /** Quota resource type */
  quotaType: string;
  /** Authoritative balance recorded on Entitlement database record */
  dbBalance: number;
  /** Mathematical sum of all append-only EntitlementLedger.changeAmount */
  ledgerSum: number;
  /** Difference between DB balance and Ledger sum (should be 0) */
  ledgerDelta: number;
  /** Available quota currently cached in Redis */
  redisAvailable: number;
  /** Active held/reserved quota in Redis */
  redisHolds: number;
  /** Total quota cached in Redis (avail + holds) */
  redisTotal: number;
  /** Difference between Redis total and DB balance (should be 0) */
  cacheDelta: number;
  /** Whether Redis cache was automatically restored from DB balance */
  repaired: boolean;
}
