/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { EntitlementLedgerItemDtoAction } from './entitlementLedgerItemDtoAction';
import type { EntitlementLedgerItemDtoQuotaType } from './entitlementLedgerItemDtoQuotaType';

export interface EntitlementLedgerItemDto {
  /** Ledger line TypeID */
  id: string;
  /** Application ID */
  appId: string;
  /** Workspace TypeID */
  workspaceId: string;
  /** Operator or target user TypeID */
  userId?: string;
  /** Quota resource type */
  quotaType: EntitlementLedgerItemDtoQuotaType;
  /** Ledger bookkeeping action */
  action: EntitlementLedgerItemDtoAction;
  /** Delta change amount (positive for grants, negative for consumes) */
  changeAmount: number;
  /** Balance immediately before mutation */
  balanceBefore: number;
  /** Balance immediately after mutation */
  balanceAfter: number;
  /** Associated source business ID */
  sourceId?: string;
  /** Financial idempotency key */
  idempotencyKey?: string;
  /** Human-readable ledger audit note */
  description?: string;
  /** Creation ISO timestamp */
  createdAt: string;
}
