/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { EntitlementResponseDtoQuotaType } from './entitlementResponseDtoQuotaType';

export interface EntitlementResponseDto {
  /** Entitlement TypeID */
  id: string;
  /** Application ID */
  appId: string;
  /** Workspace TypeID */
  workspaceId: string;
  /** Quota resource type */
  quotaType: EntitlementResponseDtoQuotaType;
  /** Historical total granted quota units */
  totalGranted: number;
  /** Historical total consumed quota units */
  totalUsed: number;
  /** Current available real-time balance */
  balance: number;
  /** Reset billing cycle */
  resetCycle: string;
  /** Next automatic quota reset ISO timestamp */
  nextResetAt?: string;
  /** Last updated ISO timestamp */
  updatedAt: string;
}
