/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponseDtoDetails } from './errorResponseDtoDetails';
import type { ErrorResponseDtoMessage } from './errorResponseDtoMessage';

export interface ErrorResponseDto {
  /** RFC 7807 URI identifying the problem type */
  type: string;
  /** RFC 7807 short, human-readable summary of problem type */
  title: string;
  /** HTTP status code (RFC 7807 status) */
  status: number;
  /** HTTP status code (standard alias) */
  statusCode: number;
  /** Machine-readable business or system error code */
  errorCode: string;
  /** RFC 7807 human-readable explanation specific to this occurrence */
  detail: string;
  /** Human-readable description or array of detailed validation messages */
  message: ErrorResponseDtoMessage;
  /** RFC 7807 URI identifying the specific request occurrence */
  instance: string;
  /** Request URI path where error occurred */
  path: string;
  /** Timestamp when error occurred in ISO 8601 format */
  timestamp: string;
  /** Optional machine-readable error context or validation errors */
  details?: ErrorResponseDtoDetails;
}
