/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type FocusflowProjectsControllerListProjectsParams = {
/**
 * Filter by workspace TypeID
 */
workspaceId?: string;
/**
 * Keyword search query against title and description
 */
search?: string;
/**
 * Filter archived projects
 */
isArchived?: boolean;
/**
 * When true, queries soft-deleted projects in the Trash Bin
 */
isTrash?: boolean;
/**
 * Max records per page
 * @minimum 1
 */
limit?: number;
/**
 * Pagination offset
 * @minimum 0
 */
offset?: number;
};
