/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type FocusflowVersionsControllerListVersionsParams = {
/**
 * Page index for pagination
 * @minimum 1
 */
page?: number;
/**
 * Limit count per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Sort ordering by version number or creation time (asc | desc)
 */
sort?: string;
};
