/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type FocusflowTemplatesControllerListTemplatesParams = {
/**
 * Filter by category (e.g. ARCHITECTURE, CLOUD_NATIVE, FINANCE)
 */
category?: string;
/**
 * Filter by tag in tags array
 */
tag?: string;
/**
 * Search keyword matching title or description
 */
search?: string;
/**
 * Filter official vs community templates
 */
isOfficial?: boolean;
/**
 * Page index
 * @minimum 1
 */
page?: number;
/**
 * Page size limit
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Sort ordering: popular (most cloned) | latest (newest created)
 */
sort?: string;
};
