/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { FormSubmissionResponseDto } from './formSubmissionResponseDto';

export interface FormSubmissionListResponseDto {
  /** List of submitted leads */
  submissions: FormSubmissionResponseDto[];
  /**
     * Total count
     * @minimum 0
     */
  total: number;
}
