/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { DedupeConfigDto } from './dedupeConfigDto';
import type { FormDefinitionResponseDtoJsonSchema } from './formDefinitionResponseDtoJsonSchema';

export interface FormDefinitionResponseDto {
  /** Form TypeID */
  id: string;
  /** Parent Application TypeID */
  appId: string;
  /** Associated workspace TypeID */
  workspaceId?: string;
  /** Public URL access key */
  formKey: string;
  /** Form display name */
  name: string;
  /** Allowed origin domains */
  allowedDomains?: string[];
  /** Whether JSONSchema dynamic validation is enabled */
  isSchemaEnabled: boolean;
  /** JSONSchema definition */
  jsonSchema?: FormDefinitionResponseDtoJsonSchema;
  /** Deduplication configuration */
  dedupeConfig?: DedupeConfigDto;
  /** Whether Turnstile verification is enforced */
  isTurnstileEnabled: boolean;
  /** Whether form is currently active */
  isActive: boolean;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}
