/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { FormSubmissionResponseDtoPayload } from './formSubmissionResponseDtoPayload';
import type { FormSubmissionResponseDtoStatus } from './formSubmissionResponseDtoStatus';

export interface FormSubmissionResponseDto {
  /** Submission TypeID */
  id: string;
  /** Parent FormDefinition TypeID */
  formDefinitionId: string;
  /** Authenticated submitter User TypeID if logged in */
  userId?: string;
  /** Calculated deduplication content hash */
  dedupeHash?: string;
  /** Submitted key-value payload */
  payload: FormSubmissionResponseDtoPayload;
  /** Submission lead lifecycle status */
  status: FormSubmissionResponseDtoStatus;
  /** Submission timestamp */
  createdAt: string;
  /** Update timestamp */
  updatedAt: string;
}
