/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { FormDefinitionResponseDto } from './formDefinitionResponseDto';

export interface FormDefinitionListResponseDto {
  /** List of form definitions */
  forms: FormDefinitionResponseDto[];
  /**
     * Total count matching filters
     * @minimum 0
     */
  total: number;
}
