/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { EntitlementReconciliationSummaryDto } from './entitlementReconciliationSummaryDto';
import type { PaymentReconciliationSummaryDto } from './paymentReconciliationSummaryDto';

export interface FullReconciliationReportDto {
  /** Unique reconciliation batch identifier */
  batchId: string;
  /** ISO timestamp when reconciliation check was executed */
  runAt: string;
  /** Operator or automated trigger identity */
  executedBy?: string;
  /** Whether all payment transactions, orders, and entitlement ledgers are 100% balanced */
  isOverallHealthy: boolean;
  /** Detailed payment orders and transactions reconciliation results */
  paymentReconciliation: PaymentReconciliationSummaryDto;
  /** Detailed entitlement double-entry conservation and cache balance results */
  entitlementReconciliation: EntitlementReconciliationSummaryDto;
  /** Consecutive discrepancy failure count */
  consecutiveFailureCount: number;
  /** Whether automated circuit breaker has been tripped due to repeated discrepancies */
  circuitBreakerTripped: boolean;
}
