/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { HealthCheckResponseDtoStatus } from './healthCheckResponseDtoStatus';

export interface HealthCheckResponseDto {
  /** Current health status of the API server */
  status: HealthCheckResponseDtoStatus;
  /** Name of the service */
  service: string;
  /** Application release version */
  version: string;
  /** Server uptime in seconds */
  uptime: number;
  /** Timestamp of the health check in ISO 8601 format */
  timestamp: string;
  /** Current runtime environment */
  environment: string;
}
