/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current health status of the API server
 */
export type HealthCheckResponseDtoStatus = typeof HealthCheckResponseDtoStatus[keyof typeof HealthCheckResponseDtoStatus];


export const HealthCheckResponseDtoStatus = {
  ok: 'ok',
  degraded: 'degraded',
  error: 'error',
} as const;
