/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payment gateway channel
 */
export type InitiatePaymentDtoGateway = typeof InitiatePaymentDtoGateway[keyof typeof InitiatePaymentDtoGateway];


export const InitiatePaymentDtoGateway = {
  WECHAT: 'WECHAT',
  ALIPAY: 'ALIPAY',
  STRIPE: 'STRIPE',
  DEV_MOCK: 'DEV_MOCK',
  LEMON_SQUEEZY: 'LEMON_SQUEEZY',
  PADDLE: 'PADDLE',
} as const;
