/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { InitiatePaymentDtoGateway } from './initiatePaymentDtoGateway';
import type { SubMerchantDto } from './subMerchantDto';

export interface InitiatePaymentDto {
  /** Target order number to be paid */
  orderNo: string;
  /** Payment gateway channel */
  gateway: InitiatePaymentDtoGateway;
  /** Return URL after user completes payment on external web cashier */
  returnUrl?: string;
  /** Client IP address */
  clientIp?: string;
  /** Customer email address for invoice / receipt */
  customerEmail?: string;
  /** Partner/sub-merchant context (ISV mode) */
  subMerchant?: SubMerchantDto;
}
