/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface InstantiateTemplateDto {
  /** Target workspace ID to create new canvas project in (falls back to header) */
  workspaceId?: string;
  /** Custom title for instantiated project (defaults to template title) */
  title?: string;
  /** Optional custom description */
  description?: string;
  /**
     * Canvas viewport width in pixels
     * @minimum 800
     */
  viewportW?: number;
  /**
     * Canvas viewport height in pixels
     * @minimum 600
     */
  viewportH?: number;
}
