/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { InviteWorkspaceMemberDtoRole } from './inviteWorkspaceMemberDtoRole';

export interface InviteWorkspaceMemberDto {
  /** Invitee email address */
  email: string;
  /** Workspace role assigned to the new member */
  role: InviteWorkspaceMemberDtoRole;
}
