/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Workspace role assigned to the new member
 */
export type InviteWorkspaceMemberDtoRole = typeof InviteWorkspaceMemberDtoRole[keyof typeof InviteWorkspaceMemberDtoRole];


export const InviteWorkspaceMemberDtoRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
} as const;
