/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { InvoiceResponseDtoStatus } from './invoiceResponseDtoStatus';

export interface InvoiceResponseDto {
  /** Invoice TypeID (inv_...) */
  id: string;
  /** Unique invoice number */
  invoiceNo: string;
  /** Associated order TypeID */
  orderId: string;
  /** Invoice title */
  title: string;
  /**
     * Invoice amount in cents
     * @minimum 0
     */
  amountCents: number;
  /** Invoice type */
  type: string;
  /** Invoice status */
  status: InvoiceResponseDtoStatus;
  /** Associated red offset credit note identifier */
  redInvoiceId?: string;
  /** Creation ISO timestamp */
  createdAt: string;
}
