/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Invoice status
 */
export type InvoiceResponseDtoStatus = typeof InvoiceResponseDtoStatus[keyof typeof InvoiceResponseDtoStatus];


export const InvoiceResponseDtoStatus = {
  DRAFT: 'DRAFT',
  ISSUING: 'ISSUING',
  ISSUED: 'ISSUED',
  FAILED: 'FAILED',
  VOIDED: 'VOIDED',
  RED_OFFSET: 'RED_OFFSET',
} as const;
