/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { LedgerConservationResponseDtoQuotaType } from './ledgerConservationResponseDtoQuotaType';

export interface LedgerConservationResponseDto {
  /** Workspace TypeID */
  workspaceId: string;
  /** Quota resource type */
  quotaType: LedgerConservationResponseDtoQuotaType;
  /** Authoritative real-time balance in Entitlement table */
  currentBalance: number;
  /** Calculated mathematical sum of all ledger changeAmounts */
  ledgerSum: number;
  /** True if currentBalance exactly equals ledgerSum (zero delta) */
  isConserved: boolean;
  /** Discrepancy delta (currentBalance - ledgerSum) */
  discrepancy: number;
}
