/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectLockDetailDto } from './projectLockDetailDto';

export interface LockStatusResponseDto {
  /** Whether the project is currently locked by an active collaborator */
  isLocked: boolean;
  /** Project ID queried */
  projectId: string;
  /** Detailed lock metadata if active, or null if unlocked */
  lock?: ProjectLockDetailDto;
}
