/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface LockHolderDto {
  /** Unique user ID holding the lock */
  id: string;
  /** Display name of lock holder */
  name: string;
  /** Email of lock holder */
  email: string;
  /** Avatar URL of lock holder */
  avatarUrl?: string;
}
