/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectLockDetailDto } from './projectLockDetailDto';

export interface LockActionResponseDto {
  /** Whether the lock action succeeded */
  success: boolean;
  /** Descriptive result message */
  message: string;
  /** Resulting lock state details */
  lock?: ProjectLockDetailDto;
}
