/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { MockTriggerSuccessDtoStatus } from './mockTriggerSuccessDtoStatus';

export interface MockTriggerSuccessDto {
  /** Internal transaction number to simulate payment success for */
  transactionNo: string;
  /** Optional simulated channel trade number */
  gatewayTradeNo?: string;
  /** Simulated payment status */
  status?: MockTriggerSuccessDtoStatus;
}
