/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Simulated payment status
 */
export type MockTriggerSuccessDtoStatus = typeof MockTriggerSuccessDtoStatus[keyof typeof MockTriggerSuccessDtoStatus];


export const MockTriggerSuccessDtoStatus = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;
