/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dispatch channel
 */
export type NotificationTemplateResponseDtoChannel = typeof NotificationTemplateResponseDtoChannel[keyof typeof NotificationTemplateResponseDtoChannel];


export const NotificationTemplateResponseDtoChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  FEISHU: 'FEISHU',
  DINGTALK: 'DINGTALK',
  WECHAT_WORK: 'WECHAT_WORK',
  WEBHOOK: 'WEBHOOK',
  IN_APP: 'IN_APP',
} as const;
