/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationLogResponseDtoChannel } from './notificationLogResponseDtoChannel';
import type { NotificationLogResponseDtoStatus } from './notificationLogResponseDtoStatus';

export interface NotificationLogResponseDto {
  /** Notification audit log TypeID */
  id: string;
  /** Parent Application TypeID */
  appId: string;
  /** Delivery channel */
  channel: NotificationLogResponseDtoChannel;
  /** Recipient identifier */
  recipient: string;
  /** Title or subject */
  title?: string;
  /** Message content body */
  content: string;
  /** Delivery status */
  status: NotificationLogResponseDtoStatus;
  /** Error details or skip reason */
  errorMsg?: string;
  /** Sent timestamp */
  sentAt?: string;
  /** Creation timestamp */
  createdAt: string;
}
