/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface NotificationQuietHoursDto {
  /** Enable quiet hours do-not-disturb */
  enabled: boolean;
  /** Quiet hours start time HH:mm */
  start: string;
  /** Quiet hours end time HH:mm */
  end: string;
  /** Timezone for quiet hours calculation */
  timezone: string;
}
