/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationLogResponseDto } from './notificationLogResponseDto';

export interface NotificationLogListResponseDto {
  /** List of notification audit logs */
  logs: NotificationLogResponseDto[];
  /**
     * Total count matching filter criteria
     * @minimum 0
     */
  total: number;
}
