/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationTemplateResponseDtoChannel } from './notificationTemplateResponseDtoChannel';

export interface NotificationTemplateResponseDto {
  /** Template TypeID */
  id: string;
  /** Parent Application TypeID */
  appId: string;
  /** Unique template business code */
  code: string;
  /** Dispatch channel */
  channel: NotificationTemplateResponseDtoChannel;
  /** Subject template */
  subjectTpl?: string;
  /** Content template with interpolation placeholders */
  contentTpl: string;
  /** Whether this template is currently active */
  isActive: boolean;
  /** Creation timestamp */
  createdAt: string;
}
