/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface OrderDiscrepancyDetailDto {
  /** Business order number */
  orderNo: string;
  /** Current order status */
  orderStatus: string;
  /** Net paid amount recorded on Order (paid - refunded) */
  orderNetPaidCents: number;
  /** Algebraic sum of all successful PaymentTransactions */
  transactionsSumCents: number;
  /** Absolute discrepancy in cents between order and transactions */
  deltaCents: number;
  /** Diagnostic reason or classification of discrepancy */
  reason: string;
}
