/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Item category type
 */
export type OrderItemResponseDtoItemType = typeof OrderItemResponseDtoItemType[keyof typeof OrderItemResponseDtoItemType];


export const OrderItemResponseDtoItemType = {
  PLAN_SUBSCRIPTION: 'PLAN_SUBSCRIPTION',
  RENDER_COMPUTE_PACK: 'RENDER_COMPUTE_PACK',
  AI_TTS_PACK: 'AI_TTS_PACK',
  STORAGE_PACK: 'STORAGE_PACK',
} as const;
