/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemResponseDtoEffectsJson } from './orderItemResponseDtoEffectsJson';
import type { OrderItemResponseDtoItemType } from './orderItemResponseDtoItemType';

export interface OrderItemResponseDto {
  /** Order Item TypeID */
  id: string;
  /** Item category type */
  itemType: OrderItemResponseDtoItemType;
  /** SKU or Plan identifier code */
  skuCode: string;
  /** Display title of the purchased item */
  title: string;
  /** Unit price in cents (fen) */
  unitPriceCents: number;
  /** Purchased quantity */
  quantity: number;
  /** Subtotal in cents (fen) */
  subtotalCents: number;
  /**
     * Declarative SkuEffect snapshot
     * @nullable
     */
  effectsJson?: OrderItemResponseDtoEffectsJson;
}
