/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Declarative SkuEffect snapshot
 * @nullable
 */
export type OrderItemResponseDtoEffectsJson = { [key: string]: unknown } | null;
