/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemResponseDto } from './orderItemResponseDto';
import type { OrderResponseDtoStatus } from './orderResponseDtoStatus';

export interface OrderResponseDto {
  /** Order TypeID */
  id: string;
  /** Unique human-readable order number */
  orderNo: string;
  /** Application ID */
  appId: string;
  /** Target workspace TypeID */
  workspaceId: string;
  /** Ordering user TypeID */
  userId: string;
  /**
     * Associated Plan TypeID
     * @nullable
     */
  planId?: string | null;
  /** Order payment status */
  status: OrderResponseDtoStatus;
  /** Total payable amount in cents */
  totalAmountCents: number;
  /** Actually paid amount in cents */
  paidAmountCents: number;
  /** Total refunded amount in cents */
  refundedAmountCents: number;
  /** Currency ISO code */
  currency: string;
  /** 15-minute countdown expiration ISO timestamp */
  expiresAt: string;
  /** Order creation ISO timestamp */
  createdAt: string;
  /** Line items belonging to this order */
  items: OrderItemResponseDto[];
}
