/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { EntitlementLedgerItemDto } from './entitlementLedgerItemDto';

export interface PaginatedLedgerResponseDto {
  /** List of ledger line records */
  items: EntitlementLedgerItemDto[];
  /** Total matched records count */
  total: number;
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total available pages */
  totalPages: number;
}
