/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Action required by the frontend client
 */
export type PaymentResponseDtoAction = typeof PaymentResponseDtoAction[keyof typeof PaymentResponseDtoAction];


export const PaymentResponseDtoAction = {
  QR_CODE: 'QR_CODE',
  REDIRECT_URL: 'REDIRECT_URL',
  SDK_PARAMS: 'SDK_PARAMS',
  MOCK_INSTANT: 'MOCK_INSTANT',
} as const;
