/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { OrderDiscrepancyDetailDto } from './orderDiscrepancyDetailDto';

export interface PaymentReconciliationSummaryDto {
  /** Total business orders audited in this reconciliation batch */
  totalOrdersAudited: number;
  /** Count of fully balanced orders with zero delta discrepancy */
  matchedOrdersCount: number;
  /** Count of orders with financial discrepancies */
  discrepantOrdersCount: number;
  /** Aggregate net paid amount across all audited orders in cents */
  netOrderPaidCents: number;
  /** Aggregate net ledger cash inflow across all transactions in cents */
  netLedgerInflowCents: number;
  /** Global net difference between order paid and transaction ledger in cents */
  discrepancyCents: number;
  /** Whether global orders and payment ledger are 100% mathematically balanced */
  isBalanced: boolean;
  /** Detailed list of orders exhibiting financial unilateral discrepancies */
  discrepancies: OrderDiscrepancyDetailDto[];
}
