/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentResponseDtoAction } from './paymentResponseDtoAction';
import type { PaymentResponseDtoGateway } from './paymentResponseDtoGateway';
import type { PaymentResponseDtoSdkParams } from './paymentResponseDtoSdkParams';

export interface PaymentResponseDto {
  /** Generated payment transaction TypeID */
  transactionNo: string;
  /** Associated order number */
  orderNo: string;
  /** Payment gateway */
  gateway: PaymentResponseDtoGateway;
  /** Action required by the frontend client */
  action: PaymentResponseDtoAction;
  /** Payment amount in currency cents */
  amountCents: number;
  /** Currency code (ISO 4217) */
  currency: string;
  /** Payment transaction status */
  status: string;
  /** QR code URL or data payload for QR_CODE action */
  qrCodeUrl?: string;
  /** Redirection URL for REDIRECT_URL action */
  redirectUrl?: string;
  /** Additional SDK parameters for mobile or client libraries */
  sdkParams?: PaymentResponseDtoSdkParams;
  /** Order expiration timestamp */
  expiresAt: string;
}
