/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface PaymentTransactionResponseDto {
  /** Transaction TypeID */
  id: string;
  /** Transaction number */
  transactionNo: string;
  /** Order ID */
  orderId: string;
  /** Gateway */
  gateway: string;
  /**
     * Channel gateway trade number
     * @nullable
     */
  gatewayTradeNo?: string | null;
  /** Transaction direction */
  direction: string;
  /** Amount in cents */
  amountCents: number;
  /** Currency */
  currency: string;
  /** Status */
  status: string;
  /**
     * Paid at timestamp
     * @nullable
     */
  paidAt?: string | null;
  /** Reconciliation status */
  reconciliationStatus: string;
  /** Created at timestamp */
  createdAt: string;
}
