/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlanResponseDtoBillingCycle } from './planResponseDtoBillingCycle';
import type { PlanResponseDtoCurrencyPricesJson } from './planResponseDtoCurrencyPricesJson';
import type { PlanResponseDtoFeaturesJson } from './planResponseDtoFeaturesJson';
import type { PlanResponseDtoTier } from './planResponseDtoTier';

export interface PlanResponseDto {
  /** Plan TypeID */
  id: string;
  /** Application ID to which the plan belongs */
  appId: string;
  /** Unique plan code identifier */
  code: string;
  /** Display name of the plan */
  name: string;
  /** Plan tier category */
  tier: PlanResponseDtoTier;
  /** Billing cycle specification */
  billingCycle: PlanResponseDtoBillingCycle;
  /** Price in smallest currency unit (cents / fen) */
  priceCents: number;
  /** Currency standard ISO code */
  currency: string;
  /**
     * Multi-currency explicit pricing matrix
     * @nullable
     */
  currencyPricesJson?: PlanResponseDtoCurrencyPricesJson;
  /** Feature flags and declarative SkuEffect definitions */
  featuresJson: PlanResponseDtoFeaturesJson;
  /** Max allowed active project slots (-1 = unlimited) */
  quotaMaxProjects: number;
  /** Cycle granted 4K render minutes */
  quotaRenderMins: number;
  /** Cycle granted AI TTS characters */
  quotaTtsChars: number;
  /** Cycle granted storage quota in bytes */
  quotaStorageBytes: string;
  /** Cycle granted general compute credits */
  quotaComputeCredits: number;
  /** Cycle max allowed exports (-1 = unlimited) */
  quotaExportCount: number;
  /** Whether the plan is active and available for purchase */
  isActive: boolean;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}
