/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Billing cycle specification
 */
export type PlanResponseDtoBillingCycle = typeof PlanResponseDtoBillingCycle[keyof typeof PlanResponseDtoBillingCycle];


export const PlanResponseDtoBillingCycle = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
  ONE_TIME: 'ONE_TIME',
} as const;
