/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformAiControllerQueryUsageLogsProvider } from './platformAiControllerQueryUsageLogsProvider';
import type { PlatformAiControllerQueryUsageLogsServiceType } from './platformAiControllerQueryUsageLogsServiceType';

export type PlatformAiControllerQueryUsageLogsParams = {
/**
 * Filter by workspace TypeID
 */
workspaceId?: string;
/**
 * Filter by AI vendor provider
 */
provider?: PlatformAiControllerQueryUsageLogsProvider;
/**
 * Filter by service capability type
 */
serviceType?: PlatformAiControllerQueryUsageLogsServiceType;
/**
 * Max records per page
 * @minimum 1
 */
limit?: number;
/**
 * Pagination offset
 * @minimum 0
 */
offset?: number;
};
