/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformAssetsControllerListAssetsType } from './platformAssetsControllerListAssetsType';

export type PlatformAssetsControllerListAssetsParams = {
/**
 * Target workspace TypeID
 */
workspaceId: string;
/**
 * Filter by asset category
 */
type?: PlatformAssetsControllerListAssetsType;
/**
 * Filter by associated Project TypeID
 */
projectId?: string;
};
