/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformFormsControllerListSubmissionsStatus = typeof PlatformFormsControllerListSubmissionsStatus[keyof typeof PlatformFormsControllerListSubmissionsStatus];


export const PlatformFormsControllerListSubmissionsStatus = {
  PENDING: 'PENDING',
  PROCESSED: 'PROCESSED',
  ARCHIVED: 'ARCHIVED',
} as const;
