/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformAiControllerListConfigsServiceType = typeof PlatformAiControllerListConfigsServiceType[keyof typeof PlatformAiControllerListConfigsServiceType];


export const PlatformAiControllerListConfigsServiceType = {
  TTS: 'TTS',
  LLM_COMPLETION: 'LLM_COMPLETION',
  LLM_CHAT: 'LLM_CHAT',
} as const;
