/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformEntitlementsControllerGetLedgerEntries1Action } from './platformEntitlementsControllerGetLedgerEntries1Action';
import type { PlatformEntitlementsControllerGetLedgerEntries1QuotaType } from './platformEntitlementsControllerGetLedgerEntries1QuotaType';

export type PlatformEntitlementsControllerGetLedgerEntries1Params = {
/**
 * Filter by workspace TypeID
 */
workspaceId?: string;
/**
 * Filter by quota resource type
 */
quotaType?: PlatformEntitlementsControllerGetLedgerEntries1QuotaType;
/**
 * Filter by ledger bookkeeping action
 */
action?: PlatformEntitlementsControllerGetLedgerEntries1Action;
/**
 * Pagination page number
 * @minimum 1
 */
page?: number;
/**
 * Pagination page size
 * @minimum 1
 */
pageSize?: number;
};
