/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformNotificationsControllerListLogsChannel } from './platformNotificationsControllerListLogsChannel';
import type { PlatformNotificationsControllerListLogsStatus } from './platformNotificationsControllerListLogsStatus';

export type PlatformNotificationsControllerListLogsParams = {
/**
 * Filter by channel
 */
channel?: PlatformNotificationsControllerListLogsChannel;
/**
 * Filter by delivery status
 */
status?: PlatformNotificationsControllerListLogsStatus;
/**
 * Filter by recipient
 */
recipient?: string;
/**
 * Max items to return
 * @minimum 1
 */
limit?: number;
/**
 * Pagination offset
 * @minimum 0
 */
offset?: number;
};
