/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformPlansControllerListPlans0BillingCycle = typeof PlatformPlansControllerListPlans0BillingCycle[keyof typeof PlatformPlansControllerListPlans0BillingCycle];


export const PlatformPlansControllerListPlans0BillingCycle = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
  ONE_TIME: 'ONE_TIME',
} as const;
