/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformNotificationsControllerGetTemplateChannel = typeof PlatformNotificationsControllerGetTemplateChannel[keyof typeof PlatformNotificationsControllerGetTemplateChannel];


export const PlatformNotificationsControllerGetTemplateChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  FEISHU: 'FEISHU',
  DINGTALK: 'DINGTALK',
  WECHAT_WORK: 'WECHAT_WORK',
  WEBHOOK: 'WEBHOOK',
  IN_APP: 'IN_APP',
} as const;
