/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformEntitlementsControllerGetLedgerEntries1QuotaType = typeof PlatformEntitlementsControllerGetLedgerEntries1QuotaType[keyof typeof PlatformEntitlementsControllerGetLedgerEntries1QuotaType];


export const PlatformEntitlementsControllerGetLedgerEntries1QuotaType = {
  RENDER_4K_MINUTES: 'RENDER_4K_MINUTES',
  AI_TTS_CHARS: 'AI_TTS_CHARS',
  STORAGE_BYTES: 'STORAGE_BYTES',
  PROJECT_SLOTS: 'PROJECT_SLOTS',
  COMPUTE_CREDITS: 'COMPUTE_CREDITS',
  EXPORT_COUNT: 'EXPORT_COUNT',
} as const;
