/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformFormsControllerListSubmissionsStatus } from './platformFormsControllerListSubmissionsStatus';

export type PlatformFormsControllerListSubmissionsParams = {
/**
 * Filter by lead status
 */
status?: PlatformFormsControllerListSubmissionsStatus;
/**
 * Max items per page
 * @minimum 1
 */
limit?: number;
/**
 * Pagination offset
 * @minimum 0
 */
offset?: number;
};
