/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformEntitlementsControllerGetLedgerEntries0Action } from './platformEntitlementsControllerGetLedgerEntries0Action';
import type { PlatformEntitlementsControllerGetLedgerEntries0QuotaType } from './platformEntitlementsControllerGetLedgerEntries0QuotaType';

export type PlatformEntitlementsControllerGetLedgerEntries0Params = {
/**
 * Filter by workspace TypeID
 */
workspaceId?: string;
/**
 * Filter by quota resource type
 */
quotaType?: PlatformEntitlementsControllerGetLedgerEntries0QuotaType;
/**
 * Filter by ledger bookkeeping action
 */
action?: PlatformEntitlementsControllerGetLedgerEntries0Action;
/**
 * Pagination page number
 * @minimum 1
 */
page?: number;
/**
 * Pagination page size
 * @minimum 1
 */
pageSize?: number;
};
