/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformPlansControllerListPlans1BillingCycle } from './platformPlansControllerListPlans1BillingCycle';
import type { PlatformPlansControllerListPlans1Tier } from './platformPlansControllerListPlans1Tier';

export type PlatformPlansControllerListPlans1Params = {
/**
 * Filter plans by subscription tier category (FREE, PRO, ENTERPRISE)
 */
tier?: PlatformPlansControllerListPlans1Tier;
/**
 * Filter plans by billing cycle specification (MONTHLY, YEARLY, ONE_TIME)
 */
billingCycle?: PlatformPlansControllerListPlans1BillingCycle;
};
