/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformOrdersControllerListOrders0Status } from './platformOrdersControllerListOrders0Status';

export type PlatformOrdersControllerListOrders0Params = {
/**
 * Filter by workspace TypeID
 */
workspaceId?: string;
/**
 * Filter by order status
 */
status?: PlatformOrdersControllerListOrders0Status;
};
