/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformOrdersControllerListOrders1Status } from './platformOrdersControllerListOrders1Status';

export type PlatformOrdersControllerListOrders1Params = {
/**
 * Filter by workspace TypeID
 */
workspaceId?: string;
/**
 * Filter by order status
 */
status?: PlatformOrdersControllerListOrders1Status;
};
