/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformPlansControllerListPlans0Tier = typeof PlatformPlansControllerListPlans0Tier[keyof typeof PlatformPlansControllerListPlans0Tier];


export const PlatformPlansControllerListPlans0Tier = {
  FREE: 'FREE',
  PRO: 'PRO',
  ENTERPRISE: 'ENTERPRISE',
} as const;
