/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformPlansControllerListPlans0BillingCycle } from './platformPlansControllerListPlans0BillingCycle';
import type { PlatformPlansControllerListPlans0Tier } from './platformPlansControllerListPlans0Tier';

export type PlatformPlansControllerListPlans0Params = {
/**
 * Filter plans by subscription tier category (FREE, PRO, ENTERPRISE)
 */
tier?: PlatformPlansControllerListPlans0Tier;
/**
 * Filter plans by billing cycle specification (MONTHLY, YEARLY, ONE_TIME)
 */
billingCycle?: PlatformPlansControllerListPlans0BillingCycle;
};
