/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformAiControllerQueryUsageLogsProvider = typeof PlatformAiControllerQueryUsageLogsProvider[keyof typeof PlatformAiControllerQueryUsageLogsProvider];


export const PlatformAiControllerQueryUsageLogsProvider = {
  AZURE_OPENAI: 'AZURE_OPENAI',
  OPENAI: 'OPENAI',
  ANTHROPIC: 'ANTHROPIC',
  DEEPSEEK: 'DEEPSEEK',
  ELEVENLABS: 'ELEVENLABS',
  VOLCENGINE: 'VOLCENGINE',
} as const;
