/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformNotificationsControllerListLogsStatus = typeof PlatformNotificationsControllerListLogsStatus[keyof typeof PlatformNotificationsControllerListLogsStatus];


export const PlatformNotificationsControllerListLogsStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  SKIPPED_BY_USER_PREFERENCE: 'SKIPPED_BY_USER_PREFERENCE',
} as const;
