/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export type PlatformShortlinksControllerListShortlinks0Params = {
/**
 * Pagination page number
 * @minimum 1
 */
page?: number;
/**
 * Pagination page size limit
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by resource type
 */
resourceType?: string;
/**
 * Filter by resource ID
 */
resourceId?: string;
/**
 * Search by slug prefix
 */
slug?: string;
/**
 * Filter by active status
 */
isActive?: boolean;
};
