/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface PresignedUploadResponseDto {
  /** Newly provisioned Asset TypeID */
  assetId: string;
  /** S3 / R2 presigned PUT upload URL */
  uploadUrl: string;
  /** Physical cloud storage object key */
  storageKey: string;
  /** Final CDN public URL once upload is confirmed */
  publicUrl: string;
  /**
     * Validity duration in seconds
     * @minimum 1
     */
  expiresInSeconds: number;
}
