/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface ProcessReversalDto {
  /** Target payment transaction number to void/reverse */
  transactionNo: string;
  /** Reason for administrative reversal / void */
  reason: string;
}
