/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface ProcessRefundDto {
  /** Target order number to refund (e.g. ORD20261002...) */
  orderNo?: string;
  /** Target parent payment transaction number (e.g. txn_01j...) */
  transactionNo?: string;
  /**
     * Amount in cents to refund (if omitted, defaults to remaining full refundable amount)
     * @minimum 1
     */
  amountCents?: number;
  /** Business or operational reason for refund */
  reason: string;
}
