/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { LockHolderDto } from './lockHolderDto';

export interface ProjectLockDetailDto {
  /** Unique lock identifier (TypeID prefix: plk_) */
  id: string;
  /** Associated project identifier */
  projectId: string;
  /** User ID of lock holder */
  lockedByUserId: string;
  /** Client session identifier of lock holder */
  clientId: string;
  /** Timestamp when lock was initially acquired */
  lockedAt: string;
  /** Timestamp when lock will expire unless renewed */
  expiresAt: string;
  /** Remaining seconds before lock expiry */
  remainingTtlSeconds: number;
  /** User profile of the lock holder */
  holder?: LockHolderDto;
}
