/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectVersionResponseDto } from './projectVersionResponseDto';

export interface ProjectVersionListResponseDto {
  /** Array of project historical version snapshots */
  items: ProjectVersionResponseDto[];
  /** Total version count matching filter */
  total: number;
  /** Current page index */
  page: number;
  /** Page size limit */
  limit: number;
}
