/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectTemplateResponseDtoDslJson } from './projectTemplateResponseDtoDslJson';

export interface ProjectTemplateResponseDto {
  /** Unique template identifier (TypeID prefix: ptpl_) */
  id: string;
  /** Application ID */
  appId: string;
  /** Template title */
  title: string;
  /** Template description */
  description?: string;
  /** Architecture category classification */
  category: string;
  /** Taxonomy tags array */
  tags: string[];
  /** Thumbnail asset URL */
  thumbnailUrl?: string;
  /** Background diagram asset URL */
  previewUrl?: string;
  /** FocusFlow DSL v1.0 state tree blueprint */
  dslJson: ProjectTemplateResponseDtoDslJson;
  /** Whether marked as official template */
  isOfficial: boolean;
  /** Whether publicly accessible in gallery */
  isPublic: boolean;
  /** Total number of times cloned into projects */
  useCount: number;
  /** Creation timestamp in ISO-8601 format */
  createdAt: string;
  /** Last update timestamp in ISO-8601 format */
  updatedAt: string;
  /** Soft-deletion timestamp if pruned */
  deletedAt?: string;
}
