/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectTemplateResponseDto } from './projectTemplateResponseDto';

export interface ProjectTemplateListResponseDto {
  /** Array of project templates */
  items: ProjectTemplateResponseDto[];
  /** Total template count matching filter */
  total: number;
  /** Current page */
  page: number;
  /** Page limit size */
  limit: number;
  /** Available category classifications across all templates */
  categories: string[];
}
