/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectVersionResponseDtoDslJson } from './projectVersionResponseDtoDslJson';
import type { VersionCreatorDto } from './versionCreatorDto';

export interface ProjectVersionResponseDto {
  /** Unique version snapshot identifier (TypeID prefix: pjv_) */
  id: string;
  /** Associated project identifier */
  projectId: string;
  /** Sequential milestone version number */
  versionNo: number;
  /** Version description or changelog notes */
  description?: string;
  /** Full FocusFlow DSL v1.0 state tree snapshot */
  dslJson: ProjectVersionResponseDtoDslJson;
  /** User ID of the snapshot creator */
  createdById: string;
  /** Creation timestamp in ISO-8601 format */
  createdAt: string;
  /** Last update timestamp in ISO-8601 format */
  updatedAt: string;
  /** Soft-deletion timestamp if moved to trash */
  deletedAt?: string;
  /** Creator user profile information */
  creator?: VersionCreatorDto;
}
