/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectResponseDtoDslJson } from './projectResponseDtoDslJson';

export interface ProjectResponseDto {
  /** Project TypeID */
  id: string;
  /** Parent workspace TypeID */
  workspaceId: string;
  /** Project title */
  title: string;
  /** Unique slug */
  slug: string;
  /** Project description */
  description?: string;
  /**
     * Viewport nominal width (5K)
     * @minimum 1
     */
  viewportW: number;
  /**
     * Viewport nominal height (5K)
     * @minimum 1
     */
  viewportH: number;
  /** Canvas 5K background diagram image URL */
  bgImageUrl: string;
  /** FocusFlow DSL state tree definition */
  dslJson: ProjectResponseDtoDslJson;
  /** Whether the project is publicly viewable */
  isPublic: boolean;
  /**
     * Total public presentation view count
     * @minimum 0
     */
  viewCount: number;
  /**
     * Monotonic incremental DSL revision number
     * @minimum 1
     */
  versionNo: number;
  /** Whether the project is currently archived */
  isArchived: boolean;
  /** Owner User TypeID */
  ownerId: string;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  /** Soft-deletion timestamp if in trash */
  deletedAt?: string;
}
