/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Full FocusFlow DSL v1.0 state tree snapshot
 */
export type ProjectVersionResponseDtoDslJson = { [key: string]: unknown };
