/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface ReconciliationHealthStatusDto {
  /** Timestamp of the most recent shadow reconciliation run */
  lastRunAt?: string;
  /** Batch ID of the most recent shadow reconciliation run */
  lastBatchId?: string;
  /** Current overall platform financial health state */
  isOverallHealthy: boolean;
  /** Current consecutive discrepancy counter */
  consecutiveFailureCount: number;
  /** Whether the circuit breaker is active */
  circuitBreakerTripped: boolean;
  /** Configured Cron schedule expression for the periodic shadow reconciliation engine */
  activeCronSchedule: string;
}
