/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * New order status
 */
export type RefundResponseDtoOrderStatus = typeof RefundResponseDtoOrderStatus[keyof typeof RefundResponseDtoOrderStatus];


export const RefundResponseDtoOrderStatus = {
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  REFUNDED: 'REFUNDED',
} as const;
