/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { RefundResponseDtoOrderStatus } from './refundResponseDtoOrderStatus';
import type { RevokedQuotaItemDto } from './revokedQuotaItemDto';

export interface RefundResponseDto {
  /** Whether refund succeeded */
  success: boolean;
  /** Newly generated refund transaction TypeID (txn_...) */
  refundTransactionNo: string;
  /** Parent initial income transaction TypeID */
  originalTransactionNo: string;
  /** Associated order number */
  orderNo: string;
  /**
     * Delta refunded amount in cents for this transaction
     * @minimum 1
     */
  refundAmountCents: number;
  /**
     * Cumulative refunded amount in cents on the order
     * @minimum 1
     */
  cumulativeRefundedCents: number;
  /** New order status */
  orderStatus: RefundResponseDtoOrderStatus;
  /** Gateway refund identifier */
  gatewayRefundNo: string;
  /** Whether associated invoice was automatically red-offset */
  invoiceRedOffset: boolean;
  /** List of revoked quotas for this refund */
  revokedQuotas: RevokedQuotaItemDto[];
}
