/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterDto {
  /** User login email address */
  email: string;
  /**
     * User password (minimum 8 characters)
     * @minLength 8
     */
  password: string;
  /** Full name or display name of the user */
  name: string;
  /** Optional initial workspace name */
  workspaceName?: string;
}
