/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ReleaseHoldDtoQuotaType } from './releaseHoldDtoQuotaType';

export interface ReleaseHoldDto {
  /** Target workspace TypeID */
  workspaceId: string;
  /** Quota resource type */
  quotaType: ReleaseHoldDtoQuotaType;
  /** Task or job identifier to release hold for */
  jobId: string;
}
