/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface ReleaseLockDto {
  /** Client identifier holding the lock */
  clientId?: string;
  /** Force release lock regardless of owner (requires workspace OWNER or ADMIN role) */
  force?: boolean;
}
