/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ReleaseHoldResponseDtoQuotaType } from './releaseHoldResponseDtoQuotaType';

export interface ReleaseHoldResponseDto {
  /** Whether hold release succeeded */
  success: boolean;
  /** Target workspace TypeID */
  workspaceId: string;
  /** Quota resource type */
  quotaType: ReleaseHoldResponseDtoQuotaType;
  /** Released job identifier */
  jobId: string;
  /** Amount refunded back to available pool */
  releasedAmount: number;
  /** New available pool balance in Redis */
  remainingAvail: number;
}
