/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface RemoveWorkspaceMemberResponseDto {
  /** Whether the removal operation succeeded */
  success: boolean;
  /** Operational result message */
  message: string;
}
