/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { RenderJobResponseDto } from './renderJobResponseDto';

export interface RenderJobListResponseDto {
  /** List of render jobs */
  items: RenderJobResponseDto[];
  /** Total count matching filters */
  total: number;
}
