/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface RenderJobResponseDto {
  /** Render job unique TypeID (rnd_...) */
  id: string;
  /** Target project TypeID */
  projectId: string;
  /** Owner workspace TypeID */
  workspaceId: string;
  /** Submitter User TypeID */
  userId: string;
  /** Resolution specification (4K / 2K / 1080P) */
  resolution: string;
  /** Framerate (fps) */
  fps: number;
  /** Output container format */
  format: string;
  /** Current job status in queue/pipeline */
  status: string;
  /** Progress percentage (0.0 - 100.0) */
  progressPercent: number;
  /** Current frame rendered */
  currentFrame: number;
  /** Total frames to render */
  totalFrames: number;
  /** Completed video download/CDN URL */
  downloadUrl?: string;
  /** Error message if job failed */
  errorMessage?: string;
  /** Elapsed rendering time in seconds */
  renderTimeSec?: number;
  /** Job creation timestamp */
  createdAt: string;
  /** Job completion timestamp */
  completedAt?: string;
}
