/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { RequestPresignedUploadDtoType } from './requestPresignedUploadDtoType';

export interface RequestPresignedUploadDto {
  /** Target workspace TypeID */
  workspaceId: string;
  /** Category of asset being uploaded */
  type: RequestPresignedUploadDtoType;
  /** Original filename with extension */
  name: string;
  /** Standard MIME type */
  mimeType: string;
  /**
     * File size in bytes
     * @minimum 1
     */
  sizeBytes: number;
  /** Optional project binding TypeID */
  projectId?: string;
}
