/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ReserveQuotaDtoQuotaType } from './reserveQuotaDtoQuotaType';

export interface ReserveQuotaDto {
  /** Target workspace TypeID */
  workspaceId: string;
  /** Quota resource type to reserve */
  quotaType: ReserveQuotaDtoQuotaType;
  /**
     * Required quota amount to hold
     * @minimum 1
     */
  amount: number;
  /** Unique background job or task TypeID */
  jobId: string;
  /**
     * Hold lease TTL duration in seconds (default: 1800s / 30m)
     * @minimum 60
     */
  ttlSeconds?: number;
}
