/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ReserveQuotaResponseDtoQuotaType } from './reserveQuotaResponseDtoQuotaType';

export interface ReserveQuotaResponseDto {
  /** Whether reservation succeeded */
  success: boolean;
  /** Target workspace TypeID */
  workspaceId: string;
  /** Quota resource type */
  quotaType: ReserveQuotaResponseDtoQuotaType;
  /** Held task or job identifier */
  jobId: string;
  /** Total units reserved in hold hash */
  reservedAmount: number;
  /** Instant remaining available units in Redis cache */
  remainingAvail: number;
  /** Hold lease expiration epoch millisecond timestamp */
  expireAt: number;
}
