/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface ReversalResponseDto {
  /** Whether reversal succeeded */
  success: boolean;
  /** Newly generated adjustment transaction TypeID (txn_...) */
  adjustTransactionNo: string;
  /** Original reversed transaction TypeID */
  originalTransactionNo: string;
  /** Associated order number */
  orderNo: string;
  /**
     * Reversed amount in cents
     * @minimum 1
     */
  reversedAmountCents: number;
  /** New order status */
  orderStatus: string;
}
