/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface RevokedQuotaItemDto {
  /** Quota resource type */
  quotaType: string;
  /**
     * Number of quota units revoked from balance
     * @minimum 0
     */
  revokedAmount: number;
}
