/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface RunReconciliationDto {
  /** Specific workspace ID to limit audit scope (leave empty for global tenant audit) */
  workspaceId?: string;
  /** Application identifier for multi-app scoping */
  appId?: string;
  /** Whether to automatically repair Redis quota cache drift from authoritative DB balance */
  autoRepairCache?: boolean;
  /** Whether to persist reconciliation status (MATCHED/DISCREPANCY) and batch ID to PaymentTransaction records */
  markTransactions?: boolean;
  /** Custom reconciliation batch identifier */
  batchId?: string;
}
