/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Delivery or skip status
 */
export type SendNotificationResponseDtoStatus = typeof SendNotificationResponseDtoStatus[keyof typeof SendNotificationResponseDtoStatus];


export const SendNotificationResponseDtoStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  SKIPPED_BY_USER_PREFERENCE: 'SKIPPED_BY_USER_PREFERENCE',
} as const;
