/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { SendNotificationResponseDtoChannel } from './sendNotificationResponseDtoChannel';
import type { SendNotificationResponseDtoStatus } from './sendNotificationResponseDtoStatus';

export interface SendNotificationResponseDto {
  /** Notification audit log TypeID */
  logId: string;
  /** Delivery or skip status */
  status: SendNotificationResponseDtoStatus;
  /** Target channel */
  channel: SendNotificationResponseDtoChannel;
  /** Target recipient */
  recipient: string;
  /** Interpolated title/subject */
  title?: string;
  /** Interpolated content body */
  content: string;
  /** Dispatch timestamp if sent */
  sentAt?: string;
  /** Error or skip reason description */
  errorMsg?: string;
}
