/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { SendNotificationDtoChannel } from './sendNotificationDtoChannel';
import type { SendNotificationDtoVariables } from './sendNotificationDtoVariables';

export interface SendNotificationDto {
  /** Dispatch delivery channel */
  channel: SendNotificationDtoChannel;
  /** Recipient identifier (email address, mobile number, user ID or webhook URL) */
  recipient: string;
  /** Target user ID for preference and quiet hours check */
  userId?: string;
  /** Notification category: CRITICAL (mandatory bypass), OPERATIONAL, MARKETING, etc. */
  category?: string;
  /** Registered template code for automatic interpolation */
  templateCode?: string;
  /** Dynamic variables for template interpolation */
  variables?: SendNotificationDtoVariables;
  /** Direct title/subject if not using a template */
  title?: string;
  /** Direct content body if not using a template */
  content?: string;
}
