/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { SettleQuotaResponseDtoQuotaType } from './settleQuotaResponseDtoQuotaType';

export interface SettleQuotaResponseDto {
  /** Whether settlement succeeded */
  success: boolean;
  /** Target workspace TypeID */
  workspaceId: string;
  /** Quota resource type */
  quotaType: SettleQuotaResponseDtoQuotaType;
  /** Settled job identifier */
  jobId: string;
  /** Actual quota units consumed and recorded in ledger */
  actualAmount: number;
  /** Quota units returned to available pool if held amount exceeded actual */
  refundedAmount: number;
  /** New database entitlement balance */
  newBalance: number;
  /** Generated immutable ledger entry TypeID */
  ledgerId: string;
}
