/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { SettleQuotaDtoQuotaType } from './settleQuotaDtoQuotaType';

export interface SettleQuotaDto {
  /** Target workspace TypeID */
  workspaceId: string;
  /** Quota resource type */
  quotaType: SettleQuotaDtoQuotaType;
  /** Task or job identifier */
  jobId: string;
  /**
     * Actual quota units consumed by task
     * @minimum 0
     */
  actualAmount: number;
  /** Optional business source reference */
  sourceId?: string;
  /** Optional consumption audit description */
  description?: string;
}
