/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ShortlinkStatsResponseDtoExpiresAt } from './shortlinkStatsResponseDtoExpiresAt';

export interface ShortlinkStatsResponseDto {
  /** Shortlink slug */
  slug: string;
  /** Target redirect destination URL */
  targetUrl: string;
  /** Live PV count (from DB / Redis) */
  pvCount: number;
  /** Live UV count (HyperLogLog estimated) */
  uvCount: number;
  /** Whether the slug was served from hot Redis cache */
  cached: boolean;
  /** Expiration date if set */
  expiresAt?: ShortlinkStatsResponseDtoExpiresAt;
}
