/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ShortlinkResponseDto } from './shortlinkResponseDto';

export interface ShortlinkListResponseDto {
  /** List of shortlink records */
  items: ShortlinkResponseDto[];
  /** Total number of records matching query */
  total: number;
  /** Current page */
  page: number;
  /** Page limit */
  limit: number;
}
