/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ShortlinkResponseDtoCreatedAt } from './shortlinkResponseDtoCreatedAt';
import type { ShortlinkResponseDtoExpiresAt } from './shortlinkResponseDtoExpiresAt';
import type { ShortlinkResponseDtoUpdatedAt } from './shortlinkResponseDtoUpdatedAt';

export interface ShortlinkResponseDto {
  /** Shortlink TypeID (slk_...) */
  id: string;
  /** Application ID */
  appId: string;
  /** Shortlink unique slug */
  slug: string;
  /** Full public short URL */
  shortUrl: string;
  /** Target destination URL */
  targetUrl: string;
  /**
     * Resource type
     * @nullable
     */
  resourceType?: string | null;
  /**
     * Resource ID
     * @nullable
     */
  resourceId?: string | null;
  /** Total Page Views count */
  pvCount: number;
  /** Unique Visitors count */
  uvCount: number;
  /** Expiration date */
  expiresAt?: ShortlinkResponseDtoExpiresAt;
  /** Whether shortlink is currently active */
  isActive: boolean;
  /** Creation timestamp */
  createdAt: ShortlinkResponseDtoCreatedAt;
  /** Last update timestamp */
  updatedAt: ShortlinkResponseDtoUpdatedAt;
}
