/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { SubMerchantDtoMode } from './subMerchantDtoMode';

export interface SubMerchantDto {
  /** Merchant mode */
  mode: SubMerchantDtoMode;
  /** WeChat Pay sub_mchid */
  subMchId?: string;
  /** Alipay app_auth_token */
  appAuthToken?: string;
  /** Stripe Connected Account ID */
  connectedAccountId?: string;
}
