/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitFormPayloadDtoPayload } from './submitFormPayloadDtoPayload';

export interface SubmitFormPayloadDto {
  /** Dynamic form submission payload key-value pairs */
  payload: SubmitFormPayloadDtoPayload;
  /** Cloudflare Turnstile token for bot protection */
  turnstileToken?: string;
}
