/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface TenantContextResponseDto {
  /** Resolved tenant workspace TypeID */
  workspaceId: string;
  /** Authenticated user identifier if present */
  userId?: string;
  /** Resolved parent application identifier */
  appId?: string;
  /** User workspace role in the current tenant scope */
  role?: string;
  /** Distributed tracing request ID */
  requestId: string;
  /** Whether soft-deleted records should be included in tenant queries */
  includeDeleted?: boolean;
}
