/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Updated channel delivery toggles grouped by category
 */
export type UpdateNotificationPreferencesDtoChannels = {[key: string]: {[key: string]: boolean}};
