/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProjectDtoDslJson } from './updateProjectDtoDslJson';

export interface UpdateProjectDto {
  /** Project visual presentation title */
  title?: string;
  /** Optional architecture overview or presentation description */
  description?: string;
  /** Canvas 5K background diagram image URL */
  bgImageUrl?: string;
  /**
     * Nominal canvas natural viewport width in pixels
     * @minimum 1
     */
  viewportW?: number;
  /**
     * Nominal canvas natural viewport height in pixels
     * @minimum 1
     */
  viewportH?: number;
  /** FocusFlow DSL v1.0 state tree definition for incremental save */
  dslJson?: UpdateProjectDtoDslJson;
  /** Whether the presentation is publicly accessible */
  isPublic?: boolean;
  /** Whether the project is archived */
  isArchived?: boolean;
}
