/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationQuietHoursDto } from './notificationQuietHoursDto';
import type { UpdateNotificationPreferencesDtoChannels } from './updateNotificationPreferencesDtoChannels';

export interface UpdateNotificationPreferencesDto {
  /** Updated channel delivery toggles grouped by category */
  channels?: UpdateNotificationPreferencesDtoChannels;
  /** Updated quiet hours settings */
  quietHours?: NotificationQuietHoursDto;
}
