/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * New role assigned to the workspace member
 */
export type UpdateWorkspaceMemberRoleDtoRole = typeof UpdateWorkspaceMemberRoleDtoRole[keyof typeof UpdateWorkspaceMemberRoleDtoRole];


export const UpdateWorkspaceMemberRoleDtoRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
} as const;
