/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { DedupeConfigDto } from './dedupeConfigDto';
import type { UpdateFormDefinitionDtoJsonSchema } from './updateFormDefinitionDtoJsonSchema';

export interface UpdateFormDefinitionDto {
  /** Form display name */
  name?: string;
  /** Allowed origin domain whitelist */
  allowedDomains?: string[];
  /** Whether JSONSchema dynamic validation is enabled */
  isSchemaEnabled?: boolean;
  /** JSONSchema definition for dynamic payload validation */
  jsonSchema?: UpdateFormDefinitionDtoJsonSchema;
  /** Deduplication configuration */
  dedupeConfig?: DedupeConfigDto;
  /** Whether Cloudflare Turnstile human verification is required */
  isTurnstileEnabled?: boolean;
  /** Whether form is active */
  isActive?: boolean;
}
