/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

/**
 * Target submission status
 */
export type UpdateSubmissionStatusDtoStatus = typeof UpdateSubmissionStatusDtoStatus[keyof typeof UpdateSubmissionStatusDtoStatus];


export const UpdateSubmissionStatusDtoStatus = {
  PENDING: 'PENDING',
  PROCESSED: 'PROCESSED',
  ARCHIVED: 'ARCHIVED',
} as const;
