/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProjectTemplateDtoDslJson } from './updateProjectTemplateDtoDslJson';

export interface UpdateProjectTemplateDto {
  /** Template display title */
  title?: string;
  /** Detailed description */
  description?: string;
  /** Category classification */
  category?: string;
  /** Taxonomy tags */
  tags?: string[];
  /** Thumbnail URL */
  thumbnailUrl?: string;
  /** Background preview URL */
  previewUrl?: string;
  /** Updated FocusFlow DSL v1.0 state tree */
  dslJson?: UpdateProjectTemplateDtoDslJson;
  /** Whether marked as official */
  isOfficial?: boolean;
  /** Whether template is publicly discoverable */
  isPublic?: boolean;
}
