/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAiProviderConfigDto {
  /** Vendor endpoint API base URL */
  endpointUrl?: string;
  /** Updated API secret key */
  apiKey?: string;
  /** Model or voice identifier */
  modelName?: string;
  /** Whether this config is default for the service type */
  isDefault?: boolean;
  /** Whether this provider config is active */
  isActive?: boolean;
}
