/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUserDto } from './authUserDto';
import type { AuthWorkspaceDto } from './authWorkspaceDto';

export interface UserProfileResponseDto {
  /** User profile details */
  user: AuthUserDto;
  /** List of workspaces the user is a member of */
  workspaces: AuthWorkspaceDto[];
  /** Currently active workspace TypeID */
  activeWorkspaceId?: string;
}
