/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface VersionCreatorDto {
  /** Unique user ID who created the version snapshot */
  id: string;
  /** Display name of user */
  name: string;
  /** User email address */
  email: string;
  /** User avatar image URL */
  avatarUrl?: string;
}
