/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface WorkspaceResponseDto {
  /** Workspace unique TypeID */
  id: string;
  /** Parent Application TypeID */
  appId: string;
  /** Workspace display name */
  name: string;
  /** URL slug */
  slug: string;
  /** Owner User TypeID */
  ownerId: string;
  /** Commercial membership tier */
  tier: string;
  /** IANA timezone */
  timezone: string;
  /** Creation ISO timestamp */
  createdAt: string;
  /** Last update ISO timestamp */
  updatedAt: string;
  /** Current user membership role in this workspace */
  role?: string;
  /**
     * Total count of active members
     * @minimum 0
     */
  memberCount?: number;
}
