/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectLockDetailDto } from './projectLockDetailDto';

export interface WorkspaceActiveLocksResponseDto {
  /** Array of active project locks within workspace */
  items: ProjectLockDetailDto[];
  /** Total count of active locks in workspace */
  total: number;
}
