/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceMemberUserDto } from './workspaceMemberUserDto';

export interface WorkspaceMemberResponseDto {
  /** Workspace membership TypeID */
  id: string;
  /** Associated workspace TypeID */
  workspaceId: string;
  /** Associated user TypeID */
  userId: string;
  /** Member role within this workspace */
  role: string;
  /** Join timestamp in ISO 8601 format */
  createdAt: string;
  /** User profile details */
  user?: WorkspaceMemberUserDto;
}
