/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FocusFlow Studio API
 * FocusFlow Mode-B SaaS Enterprise API Contract (statically generated via TypeScript AST and DTO reflection)
 * OpenAPI spec version: 1.0.0
 */

export interface WorkspaceMemberUserDto {
  /** User TypeID */
  id: string;
  /** User email */
  email: string;
  /** User display name */
  name: string;
  /** User avatar URL */
  avatarUrl?: string;
}
